### ISSUE TITLE
[Feature] Add support for VeraCrypt volumes

### ISSUE THREAD

**Issue by Atrate** [hardcore-sushi/DroidFS#1]
It would be nice if the app supported the VeraCrypt volume format, seen as it is used quite extensively.

**Comment by hardcore-sushi** [comment]
Yes but that's not the the priority for now since this kind of volume is not cloud-friendly unlike file-based encryption systems like gocryptfs or cryfs.

**Comment by bingoxo** [comment]
check out https://play.google.com/store/apps/details?id=com.sovworks.eds.android , it supports veracrypt
