### ISSUE TITLE
Add and option to open a volume with fingerprint OR password

### ISSUE THREAD

**Issue by CodeCubeNeo** [hardcore-sushi/DroidFS#100]
Hello! At least as far as i have found out, once you save a password hash using a fingerprint you can't open a volume with a password anymore (unless you click to forget the password). I guess my idea is to be able to do both, unlock a volume with a fingerprint or a password (for situations where you cant put your finger on the sensor, but can type (dirty fingers for example).

**Comment by hardcore-sushi** [comment]
Good idea, how would the interface behavior change?

**Comment by CodeCubeNeo** [comment]
If I press cancel on the fingerprint request it should promt me for the password, just like it usualy does, instead of not opening anything (two example apps that do this are aegis authenticator and keepassdx if you would like to see for yourself).

**Comment by hardcore-sushi** [comment]
You're right it should definitely do that.

**Comment by hardcore-sushi** [comment]
Done: 91de54018d9f0807354f3226dd57585475204bf6
The fix should be included in the next DroidFS release.
