### ISSUE TITLE
Add Spanish translation, i can help if you want.

### ISSUE THREAD

**Issue by cyanwolfg** [hardcore-sushi/DroidFS#102]
I really like this app and I understand basic English, so I have no problem using it, but I think adding other translations can help other people who want to use the app in their native language.

I can help translate this app if you want, the only problem is that I don't know much about how to use GitHub beyond posting issues. I imagine that to do this I must modify the strings.xml file but I don't know the rest of the procedure.

**Comment by hardcore-sushi** [comment]
Any translations are welcome. If you don't know how to use GitHub or even git that's not a problem. Just send me a translated version of `app/src/main/res/values/strings.xml` and `app/src/main/res/values/arrays.xml`. You can take a look at `app/src/main/res/values-ru` and `app/src/main/res/values-pt-rBR` for examples. Don't hesitate to ask if you have any questions.

I think I should add a guide for translators who are unfamiliar with git in this repository.

**Comment by cyanwolfg** [comment]
Adding a small guide to translate will be something very appreciated and maybe it can help for many people who want to have the application in their languages.

I made the spanish translation, but I don't know how to send to you since github doesn't support .xml file attachments.

**Comment by hardcore-sushi** [comment]
I added the translation: 2697eaf11b2d51a6b22a3597e23006dd95289aa1 It should be available in the next DroidFS release.
Thank you very much for your contribution ❤️
