### ISSUE TITLE
[Feature Request] Option to keep several volumes open

### ISSUE THREAD

**Issue by ghost** [hardcore-sushi/DroidFS#105]
Option to keep volumes always open even after exiting.

Just like [cryptomator](https://cryptomator.org) where one volume need not to be closed to be able to open another volume.

**Comment by hardcore-sushi** [comment]
How is it different from [this feature](https://github.com/hardcore-sushi/DroidFS#keep-volume-open-when-the-app-goes-in-background)?

**Comment by cyanwolfg** [comment]
I imagine it would refer to being able to open multiple volumes at the same time.

**Comment by tampos4** [comment]
> How is it different from [this feature](https://github.com/hardcore-sushi/DroidFS#keep-volume-open-when-the-app-goes-in-background)?

![be5ad10e-5f37-4770-a1e8-e8d688857877](https://user-images.githubusercontent.com/103326242/162602638-d2f56df8-6929-4d6d-8e34-fa94fc3f7d87.jpg)


> I imagine it would refer to being able to open multiple volumes at the same time.

Yes.

**Comment by hardcore-sushi** [comment]
Done: 1a1d3ea570781ed12472bb7378bf4b93e26b78f6
