### ISSUE TITLE
Feature Request: Use icons instead text

### ISSUE THREAD

**Issue by cyanwolfg** [hardcore-sushi/DroidFS#107]
This is more of a design request than a functional one so it may not be important or urgent to implement.

I think adding a small fingerprint icon next to the volume names instead of displaying the "password hash saved" text. Even on volumes without a saved hash, a key icon could be included to represent password usage.

**Comment by hardcore-sushi** [comment]
Done: 72cce1d7e1909fd83a13d1ab93a15919a7076594
