### ISSUE TITLE
Add option to unlock via PIN

### ISSUE THREAD

**Issue by sukualam** [hardcore-sushi/DroidFS#108]
Can you add new unlock option with PIN? I think unlock with typing password is inconvenient for me. atleast add that feature for someone like me. thx. good app btw.

**Comment by hardcore-sushi** [comment]
Nothing prevents you from composing your password with only numbers. How would that be different?

**Comment by sukualam** [comment]
yeah, but it shown qwerty keyboard, i need keypad layout , just like unlock screen

**Comment by hardcore-sushi** [comment]
Done: 53f28e94750ae66dfff871956e55406588e8a625
