### ISSUE TITLE
[Question] Is there any timeline for implementation of cryfs

### ISSUE THREAD

**Issue by tampos4** [hardcore-sushi/DroidFS#113]

**Comment by hardcore-sushi** [comment]
I really wish DroidFS could support CryFS but I'm the only developer of this project and there are so many feature requests (😟 https://github.com/hardcore-sushi/DroidFS/issues). I currently don't have time to work on implementing these new features, fixing bugs, keeping libraries up to date, and at the same time working on CryFS support.

**Comment by hardcore-sushi** [comment]
DroidFS v2.0.0-alpha1 has been released with experimental CryFS support, I think we can close this now.
