### ISSUE TITLE
Unable to access folders 

### ISSUE THREAD

**Issue by BristolPiggy** [hardcore-sushi/DroidFS#115]
OS: Lineage Miatoll Custom ROM
Device: Xiaomi Note 9 Pro
Platform: Android 11
DroidFS version: 1.9.1

Issue: have set up two folders within DroidFS and they had been functioning as expected prior to this morning.  However, since this morning app no longer recognises password or fingerorints to open the drives and, as far as I can see there is no way to reset the password or reconfigure it. This leaves me assuming that all media stored over the last few months is lost. Password was saved within keepass file and in written form, and is being entered correctly. 

The only issue I have experienced recently was the phone inexplicably wiping half the apk's and corresponding applications from my device. Log files show the phone ran low on battery, was placed on charge, and when fully charged updated its software, destroying loaded applications.

Anyone have any ideas how I may go about retrieving the stored data or have I lost access and the contents?

**Comment by hardcore-sushi** [comment]
You should try copying your encrypted volumes to your computer and opening them with the original gocryptfs program. If they still won't open, then they could have been corrupted.

**Comment by creeper451** [comment]
i had the same issue 2 month ago but i figured out that when i changed the password of the volume i forgot to put a new one and the app accepted it and when i tried to open the volume it failed so i changed it and left the current password box empty and enter a new password it worked so i don't know maybe that will help.
