### ISSUE TITLE
The application crashes in the new display mode (v.1.10.0)

### ISSUE THREAD

**Issue by cyanwolfg** [hardcore-sushi/DroidFS#120]
Hi, I am testing the new version and I found a problem when new display mode (in grid) and enter a folder with many images (about 100 or 200) when I scroll down the application slows down and finally crashes. With the list view this does not happen.

Also in some occasions the application crashes when entering and exiting quickly from a folder with many thumbnails, this happened to me only once in list mode.

The maximum size for displaying thumbnails is set to 10mb.

**Comment by hardcore-sushi** [comment]
Thanks for the bug report, it should have been fixed with [v1.10.1](https://github.com/hardcore-sushi/DroidFS/releases/tag/v1.10.1). If it still doesn't work for you, feel free to reopen this issue.
