### ISSUE TITLE
Arabic translation

### ISSUE THREAD

**Issue by Muhmmad14333653** [hardcore-sushi/DroidFS#122]
Hello sir, can you add my arabic translation for DroidFS?
I don't know how to add the files into the code so i am going to send the files in a zip file if you don't mind. thank you for this amazing work.
[arabic for droidfs.zip](https://github.com/hardcore-sushi/DroidFS/files/8547481/arabic.for.droidfs.zip)

**Comment by hardcore-sushi** [comment]
Done: b7ab267d16cce9ab8fa3d96f1b0c69722dcd1115
Thank you very much for your contribution!
