### ISSUE TITLE
video player bug

### ISSUE THREAD

**Issue by creeper451** [hardcore-sushi/DroidFS#132]
it's only in right to left languages it's hard to explain so i'm going to upload a video if you don,t mind
[recording_20220507_141031_1.zip](https://github.com/hardcore-sushi/DroidFS/files/8645025/recording_20220507_141031_1.zip)

**Comment by hardcore-sushi** [comment]
Good finding. The bug should have been fixed: 5144947a4a129feaaae79d6531baa914b988acd8
