### ISSUE TITLE
data acces as mount storage

### ISSUE THREAD

**Issue by remydev** [hardcore-sushi/DroidFS#138]
Hello
I'm sorry, I don't understand how to do this.

I want to be able to access the files as a mount point, so once the password is completed, the apps can read and write directly.

The application I want to use to manipulate the files is obsidian.

Is this possible ?

**Comment by hardcore-sushi** [comment]
Yes, this should be possible, but you will need root access for this. Moreover, it is not really related to DroidFS since the purpose of the application is precisely to allow the opening of encrypted volumes without mounting them. You can try running the original gocryptfs program on your device as root to be able to mount volumes. (see [this](https://forum.xda-developers.com/t/native-arm-static-linux-binaries-for-android-cryptsetup-encfs-testdisk-photorec.3709380/page-4#post-76462538))

**Comment by fnfontana** [comment]
I was just about to create the same issue here, I also feel lack of the possibility of mount a virtual volume to use with other apps, specially Obsidian.

**Comment by fnfontana** [comment]
> Yes, this should be possible, but you will need root access for this. Moreover, it is not really related to DroidFS since the purpose of the application is precisely to allow the opening of encrypted volumes without mounting them. You can try running the original gocryptfs program on your device as root to be able to mount volumes. (see [this](https://forum.xda-developers.com/t/native-arm-static-linux-binaries-for-android-cryptsetup-encfs-testdisk-photorec.3709380/page-4#post-76462538))

Interesting! My suggestion is to add the option to mount the volume for rooted devices, you could this in the dangerous options with a disclaimer. It may be less secure, but will be very practiacal.

**Comment by hardcore-sushi** [comment]
It's not as simple as adding an option. Mounting a volume requires the original gocryptfs program. DroidFS does not include this program but a modified version adapted as a library (without all the FUSE stuff). If you want to mount a volume, all you have to do is compile gocryptfs for Android and run it as root.

**Comment by fnfontana** [comment]
> It's not as simple as adding an option. Mounting a volume requires the original gocryptfs program. DroidFS does not include this program but a modified version adapted as a library (without all the FUSE stuff). If you want to mount a volume, all you have to do is compile gocryptfs for Android and run it as root.

I understand it. I'm not yet familiarized with android development enviroment but i will give it a try. Thank you.

**Comment by remydev** [comment]
For now, i'm not ready to root a compile application for my phone.

For the record : 
As i can see, the best way to get secure and easy tools is to wait for the next version of cryptomator

https://github.com/cryptomator/android/issues/35
