### ISSUE TITLE
[Feature Request] opening containers using face recognition

### ISSUE THREAD

**Issue by creeper451** [hardcore-sushi/DroidFS#139]
I have a Hawaii y5 2018 it supports face recognition but it doesn't have a fingerprint sensor it would be great if i could save the password hash using my face instead of having to type the password every time, if I'm in a hurry it wouldn't be possible, i tried using the numeric keypad it's fast but I don't feel comfortable creating a container with numbers only, it may weaken the encryption.

**Comment by creeper451** [comment]
![Screenshot_20220601-150952_1](https://user-images.githubusercontent.com/92668459/171403661-2db60191-2ef1-40d2-abff-6ea8dfc52c30.png)
I got this error

**Comment by hardcore-sushi** [comment]
Yes, it was the same situation with the fingerprint sensors in the beginning. It can be fixed, but not by app developers.
