### ISSUE TITLE
No ability to create volumes

### ISSUE THREAD

**Issue by johncarterofmars** [hardcore-sushi/DroidFS#141]
I feel pretty silly that I am missing this. I installed DroidFS on LOS 19.1 and went to create a volume. However, there is no option to create. There is only an option to add an existing volume. 

Am I missing something very silly for this? 

Thank you.
![Untitled](https://user-images.githubusercontent.com/17039716/174314831-f8c5e7cf-8975-4a6e-81f0-2fdea9a64249.png)

**Comment by hardcore-sushi** [comment]
If you select an empty or non-existent folder, DroidFS will create a volume in that location.

**Comment by johncarterofmars** [comment]
Thank you. That was the issue. I put it in a folder with other items. Thank you very much.
