### ISSUE TITLE
-plaintextnames

### ISSUE THREAD

**Issue by hogAlert** [hardcore-sushi/DroidFS#15]
I'm trying to open a volume that has been created without obscured file names (created with gocryptfs option: -plaintextnames)
When I can open it with DroidFS it shows as empty.
I suspect this might be because of the missing .diriv file (filename encryption hash)?
Can DroidFS open such volumes? If it's the missing .diriv, is it possible to create an equivalent file for a plain text volume?

**Comment by hardcore-sushi** [comment]
Yes indeed, DroidFS can't open volumes with plain file name yet. I could add a support for it in the future. Pull requests are welcome ;)

**Comment by hardcore-sushi** [comment]
OK, you can now open such volumes since DroidFS v1.4.2
Enjoy ;)

**Comment by hogAlert** [comment]
Seems to be working well, thank you :) 👍
