### ISSUE TITLE
[Bug] Screen rotation stop encryption/decryption

### ISSUE THREAD

**Issue by cyanwolfg** [hardcore-sushi/DroidFS#150]
I found that if I try to encrypt a large file and when DroidFS do the encrypt (or decrypt) procces and if for some reason the screen rotate the process stop and the notification disappear.

I don't know if this is something about my device or a real bug on the app.

**Comment by hardcore-sushi** [comment]
Thanks for the bug report, it should have been fixed with 8709abd7d7ed5f74dbfb7b51cf08a23495ac7d65.
