### ISSUE TITLE
gocryptfs.conf compatibility problem between DroidFS and SiriKali / cppcryptfs with passwords containing special characters

### ISSUE THREAD

**Issue by arthwer** [hardcore-sushi/DroidFS#154]
Using gocryptfs with SiriKali on Linux and cppcryptfs on Windows. When moving cipher directories to Android and applying DroidFS I obtain a message "Failed to open the volume. Please check your password". There seems to be an issue if the password contains special characters e.g. something like §, since I tried it with a simpler password like helloworld and it worked. The other way around, i.e. creating a cipher directory with DroidFS using special characters and copying it to Linux using SiriKali or Windows using cppcryptfs resulted in password errors as well. Just copying EncryptKey and Salt between the different gocryptfs.conf files resulted again to the same problem (N,R,P,KeyLen are the same everywhere). As a workaround I could change my password but I would like to avoid it as it requires decrypting and encrypting all my data.

**Comment by hardcore-sushi** [comment]
I was able to reproduce the bug on v1.10.1 but it seems to have been fixed in v2.0.0, can you confirm that the new version works?

Also, changing the gocryptfs volume password does not require you to re-encrypt all your data, it will just re-encrypt the master key in the configuration file.

**Comment by arthwer** [comment]
Many thanks hardcore-sushi for the quick response. 

Downloaded and installed v2.0.0-alpha1 from https://forge.chapril.org/ and it worked. 

(Thanks also for the info on the not required re-encryption - I am a crypto-newbie ;-)
