### ISSUE TITLE
To open pdf files with external pdf-apps via "Open with external app" link seems not to work for all apps

### ISSUE THREAD

**Issue by arthwer** [hardcore-sushi/DroidFS#156]
When trying to open a pdf file via "Open with external app" using different pdf viewers it seems to work for e.g. with Librera PRO, whereas others (e.g. MuPDF viewer or Foxit PDF Editor) don't work i.e. don't open the file (MuPDF shows a message "Dismiss").
All  apps have permissions to access files and media and work properly on opening files in "normal" directories via a file browser.

**Comment by hardcore-sushi** [comment]
Which DroidFS version are you using? Can you send the PDF file(s) that triggers this bug? Can you also show the error message or logcat of the PDF viewers that don't work?

**Comment by arthwer** [comment]
Sorry hardcore-sushi, forgot to mention: I used v2.0.0-alpha1 from https://forge.chapril.org/ . Furthermore, when first exporting the pdf file from the cipher-directory with DroidFS, opening then the deciphered file is working with all pdf apps mentioned above.
I will do further testing with logcat etc. later when I have a bit more time, hopefully today.

**Comment by arthwer** [comment]
Here a test run with the droidfs-156_org.pdf file (took our conversation from above and pasted it into libreoffice writer to generate the pdf). Generated thereof the cipher pdf droidfs-156.pdf with gocryptfs on linux, moved it to android to my cipher folder. Started alogcat and then opened the cipher folder with droidfs. Then clicked on "Open with external app" button to open the droidfs-156.pdf with MuPDF and obtained an error message. Took a screenshot thereof and saved the alogcat file. Via encrypt/export moved the deciphered pdf file to another folder and opened it without a problem with MuPDF.
Attached are the original pdf droidfs-156_org.pdf, the screenshot of the error message as well as the alogcat file (please note: I am not much familiar with android, so I hope the logcat file is of any help for you). Please let me know if you need any further infos. Thanks.
[droidfs-156_org.pdf](https://github.com/hardcore-sushi/DroidFS/files/9042255/droidfs-156_org.pdf)
![Screenshot_20220705-002026](https://user-images.githubusercontent.com/106071892/177223385-0ea3c72a-16b0-4fd7-8293-e94e8dd8ba59.jpg)
[alogcat.2022-07-05-00-21-25+0200.txt](https://github.com/hardcore-sushi/DroidFS/files/9042260/alogcat.2022-07-05-00-21-25%2B0200.txt)
.

**Comment by hardcore-sushi** [comment]
OK, it should be fixed with 11cc15536fc224fead2c9d936934a87712a45cfe. The patch will be included in the next DroidFS release. Feel free to reopen this issue if the bug is still present.
