### ISSUE TITLE
Big logo UI issue

### ISSUE THREAD

**Issue by solokot** [hardcore-sushi/DroidFS#16]
Hello!

On phones with not very large screens, the logo takes up too much space, pushing the main menu into the scrolling area. For example, a screenshot of the Xiaomi Redmi 5 phone is shown. Characteristics of its screen:
Size | 5.7 inches, 83.8 cm2 (~75.9% screen-to-body ratio)
Resolution | 720 x 1440 pixels, 18:9 ratio (~282 ppi density)
![BigLogo-UI-issue](https://user-images.githubusercontent.com/25316928/110328169-070ad980-802c-11eb-95dd-bf03d077c129.jpg)

**Comment by hardcore-sushi** [comment]
Yes, that's the desired behavior. The logo is displayed dynamically to fit the height of the screen divided by a certain factor. This factor is currently 2.2: https://github.com/hardcore-sushi/DroidFS/blob/e63981c788b4f753458c88a592267aeceae5df82/app/src/main/java/sushi/hardcore/droidfs/MainActivity.kt#L27
You can increase it to reduce the size of the logo if you want.

**Comment by hardcore-sushi** [comment]
Fixed with 1.4.3
