### ISSUE TITLE
Animated GIFs larger 5mb aren't displayed

### ISSUE THREAD

**Issue by emmerichel** [hardcore-sushi/DroidFS#160]
Any GIF larger than 5mb is animated only in thumbnail preview, not when opened.

**Comment by hardcore-sushi** [comment]
Yes this is a Glide bug, it should be fixed when the dependency version is updated in DroidFS.

**Comment by hardcore-sushi** [comment]
The bug should have been fixed since 8f5afca8239c729f3cd5c35d13d9750c92934aaf. Feel free to reopen this issue if you still have this problem.

**Comment by hardcore-sushi** [comment]
Do you use `v2.0.0-alpha2`? If so, can you share the files that cause the problem and the logcat when opening these files please?
