### ISSUE TITLE
Allow to change password by confirming with the old password instead with the fingerprint hash

### ISSUE THREAD

**Issue by xfarrow** [hardcore-sushi/DroidFS#164]
If we have an encrypted storage with fingerprint unlock, we can access the storage either by password or by fingerprint, but we cannot change the storage's password and confirming the action by inserting the old password, as how it works with a storage without fingerprint hash.

**Comment by hardcore-sushi** [comment]
Yes, it's because I don't know how to make good user interfaces. Currently, you need to click "Forget password" in the menu to be able to change the volume password by entering the current one instead of authenticating by fingerprint. I would be glad to hear your idea on how to design an interface that will allow the user to use both methods to change the password.

**Comment by xfarrow** [comment]
Hi, first of all thank you for developing and actively mantaining this awesome project, and thank you for wanting to hear my opinion :)

First, in my opinion, I'd say that "forget password" might be a bit misleading, 'cause it actually forgets the fingerprint, whereas the password is still there.

For the user interface I am no expert, but my suggestion is the following: The changing password Activity for volumes with fingerprint unlock can be the same of the Activity for volumes without fingerprint unlock, with an added `Checkbox` under the "Current password" `Inputbox`  that could go like "or use fingerprint". If the Inputbox is checked, then execute the same instructions that are currently executed, otherwise execute the actions that would be executed if the volume was not unlock-eable by fingerprint.

Hope these solutions might help you come up with something even better!

**Comment by hardcore-sushi** [comment]
> First, in my opinion, I'd say that "forget password" might be a bit misleading, 'cause it actually forgets the fingerprint, whereas the password is still there.

You're absolutely right, I should change it to "Forget fingerprint" or something.

Thanks for this good idea. I think it would be even better the other way round: hide the password EditText by default if the fingerprint is saved but show it if the "Use password" CheckBox is checked.

**Comment by hardcore-sushi** [comment]
Problems should be solved with 4df108673404d0cdb3d1c928c1747ba133a14bbc. Feel free to reopen this issue if the next DroidFS release still doesn't suit you.
