### ISSUE TITLE
Error after upgrading from 1.4.2 -> 1.10.1

### ISSUE THREAD

**Issue by lapecoravolante** [hardcore-sushi/DroidFS#166]
Hi,
after upgrading the app I get this error when I try to save the password hash with fingerprint:

UnrecoverableKeyException - Failed to obtain information about key. Can't load encryption key

What am I supposed to do?

**Comment by hardcore-sushi** [comment]
If it's available, you can try clicking "Reset Hash Storage" in the error dialog. If that doesn't work, you can try erasing app data, but beware, this will delete all your hidden volumes if you have any.

**Comment by lapecoravolante** [comment]
Already tried, the reset goes well but nothing changes.
I've also tried to clean all data and I've re-created the archive but nothing happened.
The only way to use the app is by entering the password manually at each login

**Comment by hardcore-sushi** [comment]
OK, do you still get the same error when uninstalling the application and then reinstalling it?
Can you also show your logcat please?

**Comment by lapecoravolante** [comment]
Ok, the issue disappears after a manual remove and reinstall operation.
Maybe there were some cache data not removed by the manual clean up task fron the Android application menu.
