### ISSUE TITLE
No file explorer found

### ISSUE THREAD

**Issue by Occamsdice** [hardcore-sushi/DroidFS#168]
When I try to add volume, I get the 'No file explorer found' popup. My device is rooted and I had removed the stock file manager and have material files installed currently but the app doesn't recognize this?

**Comment by hardcore-sushi** [comment]
That's not a problem with DroidFS. A file explorer must be able to handle [Intent.ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE) to have a chance to be selected by the system as a directory picker for DroidFS. Material files doesn't implement it, as can be seen [here](https://github.com/zhanghai/MaterialFiles/blob/master/app/src/main/AndroidManifest.xml#L116-L122). Therefore, you need another file manager to be able to select a directory from DroidFS. However, note that directory picking is not necessary. If you really don't want to use another file explorer, you can just copy-paste or handwrite the volume path.
