### ISSUE TITLE
Volume's Total size UI issue

### ISSUE THREAD

**Issue by solokot** [hardcore-sushi/DroidFS#17]
Hello!

The total size of the volume does not fit in the info line. The localized string is only 2 characters longer than the original English, which hardly matters. Here is a screenshot from the screen of Xiaomi Mi 9 Lite phone:
Screen size (inches) | 6.39
Resolution | 1080x2340 pixels
Pixels per inch (PPI) | 403
![TotalSize-UI-issue](https://user-images.githubusercontent.com/25316928/110329163-51408a80-802d-11eb-8b8f-df411b05bf33.jpg)

By the way, there is no logo size issue on this screen (https://github.com/hardcore-sushi/DroidFS/issues/16).

**Comment by hardcore-sushi** [comment]
OK, this issue should be solved with [4c66251](https://github.com/hardcore-sushi/DroidFS/commit/4c66251b708761a19fd970ef3e7d3f77d3dbcb73).
The fix will be included in the next release.
