### ISSUE TITLE
videoplayer crash after a few seconds and DroidFS shows "empty directory"

### ISSUE THREAD

**Issue by jetta20162** [hardcore-sushi/DroidFS#170]
when watching a video with the internal player after a few seconds the video player crashes and the volume shows "empty directory". All files are gone until I close the volume and open it again. happening on mp4 files. DroidFS version 1.10.1 and the volume is stored on an external microsd card. Android 11 (LineageOS 18)

**Comment by hardcore-sushi** [comment]
OK, this may have been fixed with 7cdfc32c31b210111b55e8ace40f115a08afc602. Can you verify this by testing with the latest alpha version?

**Comment by jetta20162** [comment]
Thanks,

i will test it asap.

Am Samstag, 8. Oktober 2022 schrieb Hardcore Sushi ***@***.***
>:
> OK, this may have been fixed with 7cdfc32. Can you verify this by testing
with the latest alpha version?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci3.googleusercontent.com/proxy/Hl5JN_wjaGRntaOSSbOwDcv6llcXuUggj4JlaUEgst2a2izSCvg7eAkdC-rdlE3NsAdwpblYrTqVM6j2ABR_jAxUgZE1y-1xDpSSc8HiSKnCnt9VRqDlcB4F7bgAwLRfLvLzmBWkKU7IOTfRBRO_j2JHJS_ykYWjYZRPeOyRfYfSPleNT-4j4pkQEfYGwOcnmhgfnfONFZJGcW5li11CHFZjYgrXbzoRJDtZeONIDY8gIJhgiw=s0-d-e1-ft#https://github.com/notifications/beacon/ACY6VP2GQJWRLLNOI4AKUVDWCFDCHA5CNFSM6AAAAAAQ6NTT66WGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSL2WGJU.gif>Message
ID: ***@***.***>
