### ISSUE TITLE
Clear 'Password' field when sending to background or locking screen

### ISSUE THREAD

**Issue by Dilshan-H** [hardcore-sushi/DroidFS#175]
First of all thanks for maintaining such a cool app 🤩

**Consider following situation**:

User type the password for a specific volume in order to mount it and right after that, tap the 'Home' key to send app to the background or instantly lock the screen because of an emergency.

**Result**:

When switching back to the app, the password remains in the password field. 
An attacker/ someone else can gain access to the volume just by tapping 'Open'.

**Expected result**:

Clear the password field whenever before mentioned events happen.

**Comment by hardcore-sushi** [comment]
You are absolutely right, it should be added for the next version.

**Comment by hardcore-sushi** [comment]
Fixed with 1e75e9a32fbc9fae7abf624737c599d806c99e2e. The patch will be included in the next release.
