### ISSUE TITLE
Adaptive app icon

### ISSUE THREAD

**Issue by w9925** [hardcore-sushi/DroidFS#176]
Please add an themed icon to the app

**Comment by hardcore-sushi** [comment]
Can you please clarify what you mean by "a themed icon" ?

**Comment by hardcore-sushi** [comment]
Ah yes, you are absolutely right, that would be a good improvement.

**Comment by hardcore-sushi** [comment]
Done with 6e500c23e55c54e63b157fdf2533e6c90733d219. The next release will have an adaptive icon.
