### ISSUE TITLE
video player in landscape mode

### ISSUE THREAD

**Issue by hanghang** [hardcore-sushi/DroidFS#18]
﻿It would be nice if you improve the video player to fit landscape orientation.

**Comment by hardcore-sushi** [comment]
Video player works for me in landscape mode. What do you want to do exactly ?

**Comment by hanghang** [comment]
When opening a video, detect the rotation information of it, rotate the player if it is landscape even if the device is in portrait mode.
is it possible? I don't know much about exoplayer.

**Comment by hardcore-sushi** [comment]
OK that could be a good idea but is it better than letting the user choose ?

**Comment by hanghang** [comment]
>  rotate the player if it is landscape even if the device is in portrait mode.

Sorry for the confusion, I mean even if the device disabled auto-rotate option.
Currently, I need to enable the device's auto-rotate option to watch landscaped videos, and re-disable it later. 
It would be great if there is an option to rotate video,
like some other players. e.g.
![IMG_20210318_170048](https://user-images.githubusercontent.com/3734451/111604612-76dd4900-8810-11eb-87e6-af9015076617.jpg)

**Comment by hardcore-sushi** [comment]
OK, maybe I could add this feature in future releases. Pull requests are welcome !

**Comment by hanghang** [comment]
I'm finding a way to compile on macos.

**Comment by ralaud** [comment]
Since Android 10 release this feature is integrated. I get this rotation lock button, if I hold my smartphone in landscape mode.

![IMG_20210329_004233.jpg](https://user-images.githubusercontent.com/27868982/112770652-f1377580-9027-11eb-9034-79724ba2e678.jpg)

**Comment by hardcore-sushi** [comment]
OK, I added this feature in v1.4.5
