### ISSUE TITLE
where are hidden volumes stored?

### ISSUE THREAD

**Issue by psychicgoldfish** [hardcore-sushi/DroidFS#183]
I know it's supposed to be hidden, but I want to move it to my SD card if possible.

**Comment by hardcore-sushi** [comment]
You should be able to copy it from the app by selecting the hidden volume and click "Copy to shared storage" in the menu, then selecting your SD card. If it doesn't work, please describe the issue.

If you have root access, you can access hidden volumes in `/data/data/sushi.hardcore.droidfs/files/volumes`.

**Comment by Tvirin** [comment]
Is it safer to store files in hidden volumes, can other applications have access to those files?

And when the application is uninstalled, are the files in the hidden volumes also deleted or do they remain?

_Thanks for the excellent app_

**Comment by hardcore-sushi** [comment]
It depends on what you mean by "safer". But no, hidden volumes are stored in the app internal storage. Other apps can't access them without root access.

When uninstalling or when you clear the app data, all hidden volumes are deleted.

**Comment by psychicgoldfish** [comment]
thanks.
