### ISSUE TITLE
File / folder list ordering

### ISSUE THREAD

**Issue by curioushedgehog** [hardcore-sushi/DroidFS#19]
At first I thought some items were not listed but it's because when listing alphabetically, upper case items are shown first, then lower case are shown after (so the order is A..Za..z).
So if you look for something beginning with w, it could be about half way down (if it's upper case) or near the very end (if it's lower case).

It would be more useful (and like every other file listing I know) to sort by letter then case i. e. aA..zZ. 

Similarly, folders seem to be included in the list mixed in with files. I realise this may just be personal preference but I am used to seeing folders at the start of the list (some managers have this as an option, most do it automatically in my experience).

Other than these suggestions, thanks for making this great app!

**Comment by curioushedgehog** [comment]
![Screenshot_20210404-090248](https://user-images.githubusercontent.com/60671673/113502502-8f45a700-9524-11eb-9a06-642f84ded553.jpg)

**Comment by hardcore-sushi** [comment]
You're right. I fixed this in [f119ccf](https://github.com/hardcore-sushi/DroidFS/commit/f119ccf477f64574529a742f5948357e47d9f4d8).

**Comment by curioushedgehog** [comment]
Working perfectly, thank you heavy metal fishy food lover ;)
