### ISSUE TITLE
v2.0.0 does not detect existing hidden container that were not remembered

### ISSUE THREAD

**Issue by nhfo** [hardcore-sushi/DroidFS#198]
I had a hidden container, say 't',  that was not remembered in app. After upgrade, when I go to create new hidden container and name it 't', the 'create volume' button no longer change to 'add volume'. If I click the button, then app shows screen to set password and select container type etc.

I did some digging on a phone where I have root access. It appears path where hidden containers are stored changed in v2.0.0. In previous versions hidden containers used to be stored under` <app data dir>/files` where as in v2.0.0.0 they are stored under `<app data dir>/files/volumes`. 

Also it appears app moves old hidden container to new path, only if it is remembered. It means any hidden container that was not remembered is not moved to new path and becomes lost. As such container files, at old path, seems intact.

Could this be fixed so that next version would move any container found at old path to new path automatically?

**Comment by hardcore-sushi** [comment]
Thanks for the bug report. 2bbf003df5479a815bdde81bca341af4e98938ce should fix this by moving all the hidden volumes found in the old path to the new location.

**Comment by nhfo** [comment]
Thank your for such a quick response. Could you please also tag it so it trickle down to fdroid.

**Comment by araafroyall** [comment]
> I had a hidden container, say 't', that was not remembered in app. After upgrade, when I go to create new hidden container and name it 't', the 'create volume' button no longer change to 'add volume'. If I click the button, then app shows screen to set password and select container type etc.
> 
> I did some digging on a phone where I have root access. It appears path where hidden containers are stored changed in v2.0.0. In previous versions hidden containers used to be stored under` <app data dir>/files` where as in v2.0.0.0 they are stored under `<app data dir>/files/volumes`.
> 
> Also it appears app moves old hidden container to new path, only if it is remembered. It means any hidden container that was not remembered is not moved to new path and becomes lost. As such container files, at old path, seems intact.
> 
> Could this be fixed so that next version would move any container found at old path to new path automatically?

Yes you are right. I downgraded and unhide volume then upgraded app again

**Comment by hardcore-sushi** [comment]
Can you please retry with v2.0.1?

**Comment by nhfo** [comment]
The fix works. Old not remembered hidden volumes can be opened again.
