### ISSUE TITLE
Unsafe Features Documentation Webpage Down

### ISSUE THREAD

**Issue by BOB74j** [hardcore-sushi/DroidFS#205]
DroidFS settings > Manage Unsafe Features > Unsafe Features Documentation opens the browser to https://git.drycat.fr/hardcore-sushi/DroidFS#unsafe-features which does not appear to be a valid web address.

Suggest changing the address to https://github.com/hardcore-sushi/DroidFS#Unsafe-Features

**Comment by hardcore-sushi** [comment]
Thank you for letting me know. Just fixed: 87ffbc3cc1231b304ac429d3d73aa16834f52443
