### ISSUE TITLE
[Bug] the app allows creating a container without a password

### ISSUE THREAD

**Issue by creeper451** [hardcore-sushi/DroidFS#206]
While experimenting, I discovered that it is feasible to generate a volume without requiring a password. I'm curious to know if this is a bug or a feature (I attempted to enter an empty password on cppcryptfs for Windows, but it was not permitted)

**Comment by hardcore-sushi** [comment]
Yes, it's a very cool feature that other implementations don't have 😎

**Comment by creeper451** [comment]
Okay good to know 👍
