### ISSUE TITLE
crash when deleting image

### ISSUE THREAD

**Issue by DanielJutz** [hardcore-sushi/DroidFS#21]
Android 9
DroidFS version 1.4.4

The app crashes when attempting to delete an image using the trash can icon while viewing that image. Does not crash when deleting via selecting with long press and then pressing the trash can icon.

https://user-images.githubusercontent.com/64782369/113772812-7eb04f00-9725-11eb-9a03-5dbc6341ceb8.mp4

**Comment by hardcore-sushi** [comment]
Good finding !
This only happens when deleting from a directory where there is only one image. I fixed the bug with https://github.com/hardcore-sushi/DroidFS/commit/a4db2740a190862ad128ba8083fc77fe35c9e54b
Thanks for this report :+1:
