### ISSUE TITLE
Embedded ExoPlayer can't successfully play videos with AV1 codec

### ISSUE THREAD

**Issue by ThachNgocTran** [hardcore-sushi/DroidFS#213]
## Description

DroidFS' built-in ExoPlayer is unable to successfully play videos encoded with AV1 codec despite this codec is officially supported through ExoPlayer extension ([documentation](https://exoplayer.dev/supported-formats.html#sample-formats)).

Error 1:

(when opening the video file)

![111](https://github.com/hardcore-sushi/DroidFS/assets/9520123/f3e8ce83-6eb7-4876-9d39-7cc9b5ab9157)

Error 2:

(after playing for a few seconds)

![222](https://github.com/hardcore-sushi/DroidFS/assets/9520123/8a30721f-caae-4258-a5c4-8117271f361d)

Details on how to embed this extension into building process of ExoPlayer: [ExoPlayer AV1 module](https://github.com/google/ExoPlayer/tree/release-v2/extensions/av1)

## Reproducibility

+ Download DroidFS via [F-Droid](https://f-droid.org/en/packages/sushi.hardcore.droidfs/), version 2.0.2.
  + gocryptfs
+ Android v10.
+ AV1 Test Video:
  + https://test-videos.co.uk/vids/sintel/mp4/av1/1080/Sintel_1080_10s_1MB.mp4
    + Caused error 2.
  + https://www.elecard.com/storage/video/CityHall_3840x2160.webm
    + Caused error 1.

**Comment by hardcore-sushi** [comment]
This works fine on my device. According to [the doc](https://developer.android.com/guide/topics/media/media-formats#video-codecs), AV1 decoder is optional on Android 10 and above. I think your device simply doesn't provide it. Can you test with another one?

I don't think adding partially redundant AV1 support is worth the cost of making the build more complex, bundling additional native dependencies and increasing the risk of supply chain attacks.

**Comment by hardcore-sushi** [comment]
I believe VLC relies on bundled ffmpeg for decoding. You can try with another video player, like the one provided with android or another exoplayer based app (without AV1 extension).

What's your device model? Are you running a custom ROM?

**Comment by ThachNgocTran** [comment]
@hardcore-sushi The **2nd video** has just been tested with an ExoPlayer-based app ([Exo Player- Video Player](https://play.google.com/store/apps/details?id=com.sportem.exoplayer&hl=en&gl=US)). Although there was not crash dialog, the video was not playable.

Here is my Android detail:

![1111111](https://github.com/hardcore-sushi/DroidFS/assets/9520123/b141c322-a84c-452f-b633-997a99e3473e)

**Comment by hardcore-sushi** [comment]
OK, as it seems more like a device-related problem than a problem with DroidFS, I'm closing this issue.

However, feedbacks for other devices and ROMs would be appreciated.
