### ISSUE TITLE
Feature Request: Integrate with default File explorer

### ISSUE THREAD

**Issue by NearestWater262** [hardcore-sushi/DroidFS#214]
Proton drive has a feature where, it automatically shows up as a drive you can browse in your Android file explorer, and if you put a password on it, you cannot (assuming because it encrypts locally)

I was thinking you can have an "unsafe" feature so that, you can unlock your droidfs container, and then it shows up in the android file explorer app and makes file operations so much easier, like Proton Drive does.

im sure there is a special word for this or term but i dont know it. this is the best i can describe.

**Comment by hardcore-sushi** [comment]
What you want is a [DocumentProvider](https://developer.android.com/guide/topics/providers/document-provider) implementation. This has already been requested in #174.
