### ISSUE TITLE
Rotating image causes metadata to be cleared

### ISSUE THREAD

**Issue by vnagel** [hardcore-sushi/DroidFS#218]
Rotating an image causes it's metadata to be cleared e.g. date, location, device. Considering that importing/exporting images to/from the encrypted volume does not clear metadata, preserving metadata upon rotation would be the most consistent IMO.

Crossing my fingers that this isn't infeasible for the same reasons as https://github.com/hardcore-sushi/DroidFS/issues/217.

**Comment by vnagel** [comment]
I only confirmed this happens for date metadata

**Comment by hardcore-sushi** [comment]
Yes that's because rotation is very poorly implemented. A bitmap is extracted from the file, manually rotated, re-encoded and then saved. It doesn't even preserve the image format if it's not JPEG or PNG.

I think this feature should be dropped, or implemented by a library.

**Comment by vnagel** [comment]
Ah gotcha. I was hoping you were doing something at the file-level that would make preserving metadata easy... I'll close this out then for the same reasons as the other issues 🙁

**Comment by hardcore-sushi** [comment]
We could probably manually copy metadata but this won't fix re-encoding related problems (image format, size...)

**Comment by vnagel** [comment]
Copying the metadata would have to be done at the file level, requiring a per-container-format metadata parser like you mentioned in https://github.com/hardcore-sushi/DroidFS/issues/217#issuecomment-1615832975 right? Bitmap doesn't contain image metadata like date, location, etc if I understand correctly.

Also, when you say it doesn't preserve image size, is that a result of possibly saving in a different format? Or is there some lossy downsizing happening somewhere?

**Comment by vnagel** [comment]
Ah, I see it's currently being compressed to 90% quality

**Comment by vnagel** [comment]
Also, I realized you could probably create an 'ExifInterface' from the existing input image byte array to get the metadata.

For my use case, I'm actually fine with the compression as long as the metadata is preserved. And the rotation feature is valuable to me. What do you think about just updating the warning message to be more clear about what is happening when you save after rotation? At least in the meantime before a library is found.

**Comment by vnagel** [comment]
Another option is to just update the exif data when doing the rotation. I believe that most image viewing applications will take the rotation stored in the exif data into account when displaying the image.
Downside is that there's a chance one views the image in an application that doesn't...

**Comment by hardcore-sushi** [comment]
You are right, the rotation should be implemented by editing metadata, without re-encoding. However this would require a metadata parser for every image formats.

>  EDIT: scratch that. I use macos, which seems like isn't straight forward/supported for this project?

You should be able to build DroidFS on macOS. Follow the instructions in [BUILD.md](https://github.com/hardcore-sushi/DroidFS/blob/master/BUILD.md) and feel free to ask if you have any issues.

**Comment by vnagel** [comment]
Unfortunate that [ExifInterface(inputStream)](https://developer.android.com/reference/android/media/ExifInterface#ExifInterface(java.io.InputStream)) doesn't support saving modified exif attributes :(
