### ISSUE TITLE
Keep Thumbnail Cache

### ISSUE THREAD

**Issue by DorianBenjamin** [hardcore-sushi/DroidFS#219]
I can't see a way to keep the thumbs cache. Please make a way to keep it, as processing it every time is resource intensive and large thumbnails can make DroidFS unstable and crash the volume while viewing media.
As i have massive volumes with hundreds of files, its a long time till all of them are generated after app launch.

**Comment by DorianBenjamin** [comment]
It is also a good idea to have it stored in the application data. Another option i have thought about, is creating a hidden folder in the volumes which contain the video and image thumbnails. That way it would be encrypted by default and could be easily loaded. I'm no developer but thats what i thought of.

**Comment by DorianBenjamin** [comment]
About the crashes: I have a folder with around 300 video items (h265 since i couldn't play AV1 init) ranging from 100kb-110mb this folder contains nested folders with another few hundred images and videos. I experienced the volume crash when i uncapped the thumbnail sizes. A while back i think i set it to 50MB and it crashed once. It wasn't the current version so im not sure you fixed this yet.

Ill attach some showcase of this issue, but im not sure how to access the logcat.

https://github.com/hardcore-sushi/DroidFS/assets/139080404/0c9dbb7f-fae6-4e2a-8791-6fac32f92155

What do you think about utilizing the hidden volumes feature for thumbnail caching? 
Maybe utilize the GPU for extracting the first frame? I apologize if i say something stupid. I'm not even sure if that's a thing on android yet.

I use ffmpegthumbnailer on linux and its pretty fast. Im not sure if you can borrow some of their work.

**Comment by hardcore-sushi** [comment]
Not all files on your video get thumbnail. I think this is because loading them throws an `OutOfMemoryError`. This is to be expected. The crash, on the other hand, is not. You can follow [this guide](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/#capture-a-bug-report-via-logcat) to capture your logcat. I can write one myself if necessary.

Yes we could use a hidden volume to store thumbnails, but that would involve complexity due to manual cache management. Using ffmpegthumbnailer is a very good idea but it might require a bit of work to get it working on android with encrypted sources.

**Comment by DorianBenjamin** [comment]
Sorry I'm unable to provide this, because of complications with developer options on my end.
But i hope i provided some valuable information and potentially a good feature request. If you want to reproduce this, all i did was to duplicate a 100mb h265 video 100 times and a 5mb image 200 times. You can also nest these folders into each other because that may cause the crash to happen sooner. I'm guessing the recursive mapping doesn't help the situation either in this case.

**Comment by hardcore-sushi** [comment]
I'm going to try to reproduce it on my side. What problems do you encounter with developer options?

**Comment by hardcore-sushi** [comment]
I'm only able to reproduce the crash when the "Map folders" option is enabled. It doesn't seem to be related to thumbnails. Can you try to reproduce it with the option disabled?

**Comment by DorianBenjamin** [comment]
> I'm going to try to reproduce it on my side. What problems do you encounter with developer options?

I cant enable it on any other profile than the owner profile. And i don't use the owner for testing.

**Comment by DorianBenjamin** [comment]
> I'm only able to reproduce the crash when the "Map folders" option is enabled. It doesn't seem to be related to thumbnails. Can you try to reproduce it with the option disabled?

Yes ill attach another video showing this.
https://litter.catbox.moe/0v1trr.mp4

However when i have mapped folders enabled and thumbnails disabled i cant crash it.
At 0:25 in my video, i felt significant lag when scrolling (the video is sped up 1.6x) but if i have thumbnails disabled the exact same stress test will remain 120fps locked all the time and more importantly it doesn't crash.

**Comment by hardcore-sushi** [comment]
> If i run adb logcat and write it to a file while reproducing the problem would that help?

Yes that's exactly what I need. It's hard to read with the grep filter. Instead you can select the DroidFS PID with:
```sh
adb logcat --pid $(adb shell ps -A | grep droidfs | awk '{print $2}')
```

On your video you open some files. Are you able to reproduce the crash without opening files?

**Comment by DorianBenjamin** [comment]
> On your video you open some files. Are you able to reproduce the crash without opening files?

Yeah i tried it again without opening them.


> adb logcat --pid $(adb shell ps -A | grep droidfs | awk '{print $2}')

Thanks for the help! Here's the new log: https://litter.catbox.moe/1f2mev.log

**Comment by hardcore-sushi** [comment]
Thank you. I don't see any critical errors in your logcat, only messages related to RAM shortage. It doesn't seem to contain the crash log. Your first capture contained ANRs and error messages but is missing information. Which version of DroidFS are you using? From GitHub or from F-Droid?

Do you know which exact action make the app crashes? If you click on "wait" and wait long enough, does it continue to run normally?

**Comment by DorianBenjamin** [comment]
> Thank you. I don't see any critical errors in your logcat, only messages related to RAM shortage. It doesn't seem to contain the crash log. Your first capture contained ANRs and error messages but is missing information. 

I'm on android 12 so the method of the logcat capture is a bit different from the guide you sent. If you tell me how to do it exactly, i can generate another one for you.

> Which version of DroidFS are you using?

I'm using 2.0.2 from F-Droid.

> Do you know which exact action make the app crashes? If you click on "wait" and wait long enough, does it continue to run normally?

I think it has trouble loading lots of items with thumbnails at once.
All I'm doing is scrolling to the bottom and to the top of the ~100 files, exit then reenter and repeat this action. Eventually it will get unstable enough that it will crash.  
If i click wait it sometimes resumes after approximately 1-2 mins but it freezes again after a few seconds mid lag spikes. Then it may or may not crash but it wont go back to being stable.


A thing i thought of, is implementing a loading queue for the thumbnails. 
DroidFS would remember the order even when going out of the folders. But this has issues because if it would hang on a thumbnail for a long time, the others wouldn't load. So maybe go through small files first. Or a better idea would be to only load thumbs that are visible on the screen and cancel processing of not visible items.

**Comment by DorianBenjamin** [comment]
Additionally here are the only two files that i use for the testing:
https://files.catbox.moe/ntheng.jpg
https://files.catbox.moe/crkywe.mkv

Both the file types have their own folder like in the video demonstration.

The image is duped 208 times
The video is: 96 times

Note that the app usually only crashes when scrolling through the images folder.

**Comment by hardcore-sushi** [comment]
> If i click wait it sometimes resumes after approximately 1-2 mins but it freezes again after a few seconds mid lag spikes. 

If the app resumes, it's not a crash but an ANR. It's strange though, as I took care to load thumbnails in a separate thread. I guess the app freezes because images are decoded by Glide on the UI thread. I'll try to fix this somehow.

> Or a better idea would be to only load thumbs that are visible on the screen and cancel processing of not visible items.

This is what is currently implemented, but it doesn't help much if you scroll too fast or if the files are too large.

**Comment by DorianBenjamin** [comment]
> If the app resumes, it's not a crash but an ANR. It's strange though, as I took care to load thumbnails in a separate thread. I guess the app freezes because images are decoded by Glide on the UI thread. I'll try to fix this somehow.

Well more often than not it actually quits, as you can see on the videos. I'm not sure if its the entire app because it then just throws me to the app start screen.

**Comment by hardcore-sushi** [comment]
Ah... If it returns to the start screen, it means it has crashed. Could you run the previous adb logcat command while you're trying to reproduce this?
You know you captured the useful thing if you see some lines related to DroidFS containing " E " (Error). For example:
```
07-15 05:56:51.978  6110 10595 E AndroidRuntime: Process: sushi.hardcore.droidfs, PID: 6110
                               ^
                               ^
```

**Comment by DorianBenjamin** [comment]
Sorry to keep you waiting. I'm traveling. I'll try when i'm available again.

**Comment by DorianBenjamin** [comment]
I think i got it but its very strange.  This one had recursive mapping endabled and it has a "beginning of crash" section.
[log4.log](https://github.com/hardcore-sushi/DroidFS/files/12244108/log4.log)

I ran a second one multiple times and it couldnt capture the crash message with recursive mapping disabled:
[log7.log](https://github.com/hardcore-sushi/DroidFS/files/12244186/log7.log)

Either way it crashes in the exact same way both times. Its just that the one with the mapping off, it cant spit out the error. In both cases the ANR message came up for a split second then disappeared then it crashed to the main screen. So i think the recursive mapping option does not influence the cause of the problem.

**Comment by DorianBenjamin** [comment]
Update: I tested it on internal storage as well and i experience the same behavior.

**Comment by hardcore-sushi** [comment]
Thank you for all this information. I only see messages complaining about high memory usage in the logs, and that seems to be the cause of the crash. However, DroidFS takes care of handling `OutOfMemoryError`s and tries to minimize its memory usage by loading only the thumbnails of visible files as well as displaying the directory contents with a RecyclerView. In addition, the runtime should limit the amount of RAM an application can request to properly handle `OutOfMemoryError`s. How much RAM does your device have?  Which Android ROM are you using?

Perhaps we can try reducing the size of the LruCache or limiting the number of concurrent thumbnails loading.

**Comment by DorianBenjamin** [comment]
I'm on Android 13.1 ArrowOS rom with 6gigs of ram.

I have read somewhere (maybe it was another issue) that you might revamp the thumbnail generation process later because the current bitmap extraction method is unreliable. 
As you find that ffmpegthumbnailer might be a good idea, do you think that something like this might fix be a solutuon or is it unrelated?

**Comment by hardcore-sushi** [comment]
I think the problem comes from the heavy loading of all files in the current directory. If that's it, it could be solved either by limiting the number of files concurrently read, or by using a more efficient thumbnailing process that doesn't require the entire file to be loaded in memory.

I'll try to create an experimental APK so you can test whether it solves the problem.

**Comment by DorianBenjamin** [comment]
Thank you!

**Comment by hardcore-sushi** [comment]
Can you please test with this experimental APK? I modified it so it only loads a maximum of 3 thumbnails simultaneously (completely arbitrarily chosen number) . It seems to fix memory issues for me.
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Download link: https://drop.underworld.fr/r/eDN7f1sS_3#dW1D1AqK4TfULlyPDGixZdwTONh0V0+WO8XU3keQnU4=
SHA256: 3cf89eb99e0577f7eabbeca5dae5e6c3ccaa2d3bd57d4b594bde1ac2c8a817cc
-----BEGIN PGP SIGNATURE-----

iHUEARYIAB0WIQS2Tv6GzuHQVPCCFxGv44Q0SkXhOgUCZNlT3gAKCRCv44Q0SkXh
OkBZAQDHrAFDGSKnvVfPZX2l83fJ9uZ9R4eXV8zW+5jcUdYc+AEAv3EfqOkgCCqg
7jvMpxGoQTSQCtEUVJmuJeTX/geZkw4=
=4Q/i
-----END PGP SIGNATURE-----

```

**Comment by DorianBenjamin** [comment]
You fixed it! I cant crash it anymore no matter how hard i try.
