### ISSUE TITLE
GIF

### ISSUE THREAD

**Issue by bitopansnwl** [hardcore-sushi/DroidFS#220]
Gif image files cannot be viewed by default like jpg or png files. I have to play slideshow then it shows.

**Comment by hardcore-sushi** [comment]
Hi, it works fine for me. What version do you use? Can you please share a gif file that triggers the bug?

**Comment by bitopansnwl** [comment]
> ?

Yes... I found that When the file size is less then it loads quickly. The size of my gif file was too big to load fast.
