### ISSUE TITLE
Crash when no file manager is found

### ISSUE THREAD

**Issue by NSTAdventure** [hardcore-sushi/DroidFS#23]
i don't want to use default file manager from google due to privacy issues pls remove this depedencies

**Comment by hardcore-sushi** [comment]
DroidFS use a custom file explorer to browse volumes. What do you call Google file manager ?

**Comment by NSTAdventure** [comment]
> DroidFS use a custom file explorer to browse volumes. What do you call Google file manager ?

i had done this experiment on ur app:
1. i disable com.google.documentsui (google file manager app)
2. Everytime i tried to explorer (create/ open volume) app will take me to main menu :(

**Comment by hardcore-sushi** [comment]
Yes you need a file manager to choose volume location. However you don't need the Google one. You can use the AOSP file manager or a custom one.

Please can you send the crash logs so I can show a warning if no file explorer is found ?

**Comment by NSTAdventure** [comment]
> Yes you need a file manager to choose volume location. However you don't need the Google one. You can use the AOSP file manager or a custom one.
> 
> Please can you send the crash logs so I can show a warning if no file explorer is found ?

omg ok 🤦

**Comment by ralaud** [comment]
> omg ok 🤦

Hi, just use the AOSP one, or something like Amaze or Simple Filemanager.

Or do you mean it is crashing, even if you installed a custom filemanager next to the disabled google filemanager?

**Comment by NSTAdventure** [comment]
> Yes you need a file manager to choose volume location. However you don't need the Google one. You can use the AOSP file manager or a custom one.
> 
> Please can you send the crash logs so I can show a warning if no file explorer is found ?

if explorer not found i will taken back to main menu that's it's

**Comment by NSTAdventure** [comment]
> > omg ok 🤦
> 
> Hi, just use the AOSP one, or something like Amaze or Simple Filemanager.
> 
> Or do you mean it is crashing, even if you installed a custom filemanager next to the disabled google filemanager?

not crash but taken me back to main menu of this app

**Comment by hardcore-sushi** [comment]
OK it's now fixed with [9f8b653](https://github.com/hardcore-sushi/DroidFS/commit/9f8b653cc71eaa6745033393f808bdc5d281de6c). You will see an error message if no file manager is found. The fix will be included in the next release.

**Comment by NSTAdventure** [comment]
> OK it's now fixed with [9f8b653](https://github.com/hardcore-sushi/DroidFS/commit/9f8b653cc71eaa6745033393f808bdc5d281de6c). You will see an error message if no file manager is found. The fix will be included in the next release.

is not that simple my lovely darling 😘

you need make droidfs able to use any file manager that i download and instal bruh 🗿

**Comment by hardcore-sushi** [comment]
It's already the case. You can pick a folder with any file manager that handles [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT_TREE).

**Comment by NSTAdventure** [comment]
> It's already the case. You can pick a folder with any file manager that handles [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent.html#ACTION_OPEN_DOCUMENT_TREE).

Hip hip hooorrraaaaaaayyyy :D

did you release this update on f-droid already?

**Comment by hardcore-sushi** [comment]
The merge request was accepted, the new version should be included in the next repo update.
