### ISSUE TITLE
LAN access?

### ISSUE THREAD

**Issue by null-python** [hardcore-sushi/DroidFS#25]
Is it possible to open a SMB server URL with this?

**Comment by hardcore-sushi** [comment]
Not natively. DroidFS is built from the original gocryptfs code which use simple file paths. Any app that connects to a SMB server will probably expose the filesystem through a FileProvider API. This API is not compatible with the original gocryptfs implementation.
See https://github.com/hardcore-sushi/DroidFS/issues/6.

**Comment by null-python** [comment]
### 😢😭
