### ISSUE TITLE
"Don't trust GitHub, verify PGP signature!" & obtainium app OK to use?

### ISSUE THREAD

**Issue by valtoree** [hardcore-sushi/DroidFS#253]
Hello there,
Ty Dev/s for making an awesome app.
ATM I just verify the sha256 before manually installing.
Is that OK to do only?
Or should I check the signature as well?

Also there is a new app - Obtainium
https://github.com/ImranR98/Obtainium
Which once you've installed an app via manual way above, android pins a certificate and enforces signature checks for apps for app updates. So u can use Obtainium to auto pull new apk from github and updates should be OK. I think. 🤷
Is this OK to use?
Or not recommended?

Thanks for reading.
Regards

**Comment by hardcore-sushi** [comment]
Verifying a checksum only verifies integrity, not authenticity. The file can still be modified if the attacker re-computes the checksum. If you verify the signature, only someone who knows the private key can modify the file.

The main problem with the Android's built-in verification is that the first installation is trusted. This means that if the first APK you download is tampered, you cannot detect it and all subsequent updates may be as well.

On the other hand, if you trust your local copy of my PGP key enough, you can be sure that the first APK you install hasn't been modified after I created it.

**Comment by valtoree** [comment]
Ty so much for reply 🙏. So I need to definitely also do the signature verification. 

So it sounds like Obtainium would be OK to use. If I've done verification properly. Ty ty. Keep up the great work. ❤️
