### ISSUE TITLE
[Feature Request] Persistent Background Session with Fingerprint Authentication (A different approach)

### ISSUE THREAD

**Issue by Anon7250** [hardcore-sushi/DroidFS#257]
Hello there!

I'd like to share an idea that could potentially address a significant inconvenience I've encountered. Currently, when dealing with the import/export of files, it's necessary to keep the screen on and DroidFS in the foreground.

And, if we enable certain unsafe features, they might be unsafe. 

So, I propose improving and merging two existing unsafe features, "keep volumes open in the background" and "allow fingerprints":

1. The purpose of fingerprint, is not to retrieve the original password hash.
1. Initiate a background service upon user password entry.
2. This background service generates an SSL certificate in the device's keystore, accessible via fingerprints.
3. The background service only responds if this SSL certificate is provided.
4. The SSL certificate facilitates quick reestablishment of connections to the DroidFS background service.
5. Once set up, when the DroidFS app returns to the foreground, users have two choices:
   1. Utilize fingerprints to retrieve the SSL certificate and maintain communication with existing background sessions.
   2. Restart the session by entering the password.

This approach would enable prolonged background execution of certain operations. For instance, users wouldn't need to keep the foreground app open when importing a large folder. Instead, they could instruct the background service to carry out the task seamlessly in the background.

**Comment by Anon7250** [comment]
I'm not sure whether this is the right place to post this idea / feature request. I am willing to help work on this idea if you are interested, too.

**Comment by hardcore-sushi** [comment]
If you want to let operations continue in the background, you just have to enable the *"Keep volume open when the app goes in background"* feature. I don't understand what more you're trying to achieve. Moreover, we can't rely on fingerprint authentication, because not all devices are equipped with fingerprint sensors and not all people have fingers.

If what you want is just to let file operations finish before locking a volume, how is it different from #157 ?

**Comment by Anon7250** [comment]
> enable the "Keep volume open when the app goes in background" feature. I don't understand what more you're trying to achieve. 

As I understand, if I enable it, then when I bring the app back to foreground, its volumes will stay open without any means of authentication

I'm simply asking for some form of authentication in this case

> If what you want is just to let file operations finish before locking a volume, how is it different from https://github.com/hardcore-sushi/DroidFS/issues/157 ?

This could support more types of asynchronous background operations. Maybe one day we can connect Termux to the backend service and allow power users to better manage their files.

> Moreover, we can't rely on fingerprint authentication, because not all devices are equipped with fingerprint sensors and not all people have fingers. 

I'm not sure but I think Android allows (in some cases) to use a PIN instead of a fingerprint to get pass that authentication screen.

I am not the expert about fingerprint authentications, or about Android Background services and whether they can communicate with SSL certificates. But I am curious whether this is doable, and whether it makes sense. Thank you.

**Comment by Anon7250** [comment]
I am hoping to see #157 solved, and feel part of this is my fault because I worked on the folder import features before.

I know it sounds nonsensical, why I am adding some unnecessary features to it, such as using a background service, and allowing volumes to stay open with some forms of authentication, which is why this is filed as a feature request.

It's a nice to have. And I would be happy to try to solve #157 first.

**Comment by hardcore-sushi** [comment]
OK, it sounds like you want a basic user authentication before bringing the application to foreground. In that case, an application lock might be appropriate. It has already been discussed [here](https://forge.chapril.org/hardcoresushi/DroidFS/issues/16).

**Comment by Anon7250** [comment]
Duplicate of https://forge.chapril.org/hardcoresushi/DroidFS/issues/16
