### ISSUE TITLE
[Feature request]  Use without storage permission

### ISSUE THREAD

**Issue by Blocked** [hardcore-sushi/DroidFS#27]
As the app can use app storage, "hidden volume", Allow the app to bypass the "Permission denied" dialog.

Alternatively, use SAF(Storage Access Framework) to  allow restricted access to a specific folder instead of all storage

**Comment by hardcore-sushi** [comment]
Yes you're right, the app should ask storage permissions only when using external volumes. I will fix it in the next release.

However, it's not possible to use SAF due to the native gocryptfs code that DroidFS relies on. See #6.

**Comment by hardcore-sushi** [comment]
Fixed with [9cf3e71](https://github.com/hardcore-sushi/DroidFS/commit/9cf3e71fd23467633f5669e4d11360511c34be47): storage permissions are only asked when using external volumes. The fix will be included in the next release.

**Comment by Blocked** [comment]
@hardcore-sushi Thanks. Curious - Is it possible to use the external volumes using the data folder pointer at `/storage/Android/data/sushi.hardcore.droidfs`? I believe no permissions are needed for that folder in latest android versions.

**Comment by hardcore-sushi** [comment]
Yes that's true, but I don't know the details with the previous Android version.

**Comment by Blocked** [comment]
In any case, I believe that folder in external volume will also be deleted, if the app is deleted. So, there isn't a distinct advantage over internal app storage. However, It does provide direct access through inbuilt file provider to the created crypt, which may be copied/backed up by the end user. 

On a side note,  I'm sure permissions can be limited per sdk level.

**Comment by hardcore-sushi** [comment]
Yes but I'dont want to restrict volumes location to the app data folder. I use some apps that do that and it's not very convenient.
