### ISSUE TITLE
Enable "mounted" mode

### ISSUE THREAD

**Issue by onoakino** [hardcore-sushi/DroidFS#285]
I would like to ask if the current version of DroidFS supports this mode. This is a premium feature from EDS-ng and it would be cool if we can also have it on DroidFS.

"Enable 'mounted' mode support on rooted devices. Enables transparent access to encrypted data which becomes available like an ordinary folder on your rooted device."

If I could already do this using DroidFS current version, please let me know. Otherwise, would like to file this as a feature request/enhancement. 

Thank you for your great work!

**Comment by hardcore-sushi** [comment]
If your device is rooted, you don't need DroidFS. Just compile gocryptfs or CryFS for Android and run them directly from a root shell. I think they're even packaged for Termux.
