### ISSUE TITLE
[BUG] App crash with Portuguese translation

### ISSUE THREAD

**Issue by Generator** [hardcore-sushi/DroidFS#29]
## Description 
If the system language is set to Portuguese (or Brazilian Portuguese), the app crashes when trying to open app settings or open container.

## Steps to reproduce
1. Set system language to Portuguese (or Brazilian Portuguese)
2. Open App Settings

**Comment by hardcore-sushi** [comment]
OK it's fixed with [d4a918c](https://github.com/hardcore-sushi/DroidFS/commit/d4a918c90634a272220e4de225b6ab460c8c36b3). Translators should not modify `sort_orders_values`.
