### ISSUE TITLE
Error creating directory from DocumentsProvider

### ISSUE THREAD

**Issue by eliasoft** [hardcore-sushi/DroidFS#290]
I just discovered this app, and I ran into this problem, which occurs when trying to create a new directory through the document provider exported by this app.
 The following video is just a brief way to illustrate the problem.  can you fix it soon?

https://github.com/hardcore-sushi/DroidFS/assets/40068066/614b5c37-0fd9-4442-a498-c5cc73bc1c42

**Comment by hardcore-sushi** [comment]
Yes it has already been reported here: #248, and already been fixed with f4e47c1827e92b60c938de62ed2f49875d152567

**Comment by eliasoft** [comment]
> Yes it has already been reported here: #248, and already been fixed with f4e47c1827e92b60c938de62ed2f49875d152567

Thanks, but when are you going to release an apk with the changes applied?

**Comment by hardcore-sushi** [comment]
When the new version is ready. If you can't wait you can build the app from source.
