### ISSUE TITLE
[USB] DroidFS doesn't have access to this path. Please try another location.

### ISSUE THREAD

**Issue by xxxcrow** [hardcore-sushi/DroidFS#291]
Hi, i'm on GrapheneOS and using use for storing the volumes
Before some update it was possible to make DroidFS to work with enabling the "compatibility mode" on GOS, but cryfs wan't working
Now none of the ways are working

Steps to reproduce:
1. Have a GOS phone
2. Enable the compatibility mode
3. Connect a USB drive
4. Open DroidFS
5. Try to create or open a volume
6. See the error about write permissions

Not sure where the error comes from, but i think it's crucial to maintain this functionality because a lot of people use it
Also, the status and some info should be probably added to the readme (like GOS compatibility and USB hacks if needed)

Thank you very much for your work and your project, if you need any help or testing/debugging i can do

**Comment by hardcore-sushi** [comment]
>  Now none of the ways are working

After you updated DroidFS or your system?

> See the error about write permissions

Do you get an error message complaining about inaccessible directory or only missing write permission?

If you have this issue with gocryptfs volumes then it's probably not the same thing as #281. Can you show your logcat while trying to open a volume on USB?

Also, what's your USB drive mount path?
