### ISSUE TITLE
LUKS encryption

### ISSUE THREAD

**Issue by Ud4ba** [hardcore-sushi/DroidFS#294]
Could this app unencrypt LUKS encrypted SD card? What other solutions there is for Linux + Android encryption ?

**Comment by hardcore-sushi** [comment]
LUKS is not supported by DroidFS, and will likely never be. EDS Lite does support it however.

The other solution is to root your device and access your encrypted SD card like you would do on desktop Linux with dm-crypt.

**Comment by hardcore-sushi** [comment]
> Are gocryptfs or CryFS accesible from my Linux PC?

Sure, they are both originally developed for Linux desktop.

> If yes how i could format my SD card that way from my Linux PC?

You can't. Gocryptfs and CryFS are overlay file systems. They work over an existing file system. You need to format your SD card with any common filesystem you like and they will work on top of it. For your use case, I'd suggest extFAT.

If you need more advices, check out my website for privacy & security consulting: https://arkensys.dedyn.io/
