### ISSUE TITLE
Can't delete original file after importing file to container

### ISSUE THREAD

**Issue by hollysheep** [hardcore-sushi/DroidFS#298]
When i add a file to a container and want to delete the original files there is the error that the file is read only. I can't find missing permissions in the settings.

I use a xiaomi mi 10 lite with lineageos 19, that is Android 12.

**Comment by hardcore-sushi** [comment]
Is DroidFS granted the "All files access" special permission?

What's the location of the volume and the imported file?

**Comment by hollysheep** [comment]
How can i do this?

Volume and file are in the infernal storage.

**Comment by hardcore-sushi** [comment]
> How can i do this?

The app should automatically ask the permission if you click on the folder icon when adding a volume. Otherwise, you can manually grant it in the system settings > Apps > Special app access > All files access > DroidFS

> Volume and file are in the infernal storage.

Do you mean the shared storage? Can you please give the full paths of both the volume and the imported file?

**Comment by hollysheep** [comment]
Permissions are granted.

Path is /storage/emulated/0/Download

**Comment by hardcore-sushi** [comment]
Ah yes, that is expected. "Download" is a special folder protected by the system that apps can't modify using standard file system API. Take a look [here](https://developer.android.com/about/versions/11/privacy/storage#file-directory-restrictions) for the official documentation.

Maybe files located here could still be deleted using the MediaStore API. What's the exact error that you get? Would you be able to share your logcat?

**Comment by hollysheep** [comment]
There is no need to invest to much time in that.
