### ISSUE TITLE
gocryptfs big filesystem stuck on load

### ISSUE THREAD

**Issue by yashikada** [hardcore-sushi/DroidFS#307]
I have 3 filesystems gocryptfs, 2 less 4GB and 1 more than 100GB.
With DroidFS I can load/mount 2 filesystems with less 4GB but when I try to load/mount filesystem with more than 100GB (many directories and many files) DroidFS stuck on load and never load the filesystem.
logcat don't show errors.
Does droidfs load all directories recursively or only load the top level? 
In my opinion it loads everything so in the case of a deep tree Droidfs is unable to load everything.
Is there a solution?

**Comment by hardcore-sushi** [comment]
Are you using the latest v2.2.0 version? Do you see the loading indicator spinning indefinitely?

If you haven't already done it, try disabling "Map folders" in the app settings.

**Comment by yashikada** [comment]
yes latest and thank you with map.folder.disabled works vert fast.
