### ISSUE TITLE
Detect more extensions

### ISSUE THREAD

**Issue by trab0cch3tt0** [hardcore-sushi/DroidFS#309]
Extensions like m4v work as videos but are not automatically taken as videos. This is a minor inconvenience but it would be nicer to be able to include them in the media player playlist and more

**Comment by hardcore-sushi** [comment]
Ah yeah unfortunately DroidFS does not know all extensions. I would like to add an editor in the app to allow users to add additional extensions but I'm still not sure how to implement it in the interface.

Before adding m4v to the list, are there any other extensions that you would like to add to the app?

**Comment by trab0cch3tt0** [comment]
So far I haven't come across any other extension
