### ISSUE TITLE
Sort menu logic issue

### ISSUE THREAD

**Issue by solokot** [hardcore-sushi/DroidFS#31]
The ascending and descending sorting menu items have a different order of items:
ascending: name, date, size
descending: name, size, date
This is unintuitive.

**Comment by hardcore-sushi** [comment]
Yes you're right. I just fixed it with [652fc98](https://github.com/hardcore-sushi/DroidFS/commit/652fc98ba4391b68c28ad0eaa19b9718b73481bd).
