### ISSUE TITLE
Forgot Password 

### ISSUE THREAD

**Issue by TheKnightThor** [hardcore-sushi/DroidFS#318]
i recently tried to open my volume by fingerprint and it crashed, tried it again and again, but the crashes continued. I finally removed my fingerprint from the volume (I read about crashes when adding new fingerprints), and now I can't remember my password and there is not an option to recover my volume.
I request the devs to please help me with this issue of Mine, It had really important things in it.

**Comment by hardcore-sushi** [comment]
If you totally forgot your password, you're pretty screwed. If you remember at least parts of it, you can try to bruteforce it.

The cause of the crash is being investigated, but even if it had been fixed, it would not have allowed you to regain access to the volume.

**Comment by TheKnightThor** [comment]
I brute forced it, Tried 1000s of combinations and finnally got it (Thankfully).
I hope you find the cause of the crash through.
Thanks for your help.
