### ISSUE TITLE
Volume removal protection or inbuilt app lock

### ISSUE THREAD

**Issue by miphilip** [hardcore-sushi/DroidFS#320]
Kindly add a protection to prevent anyone with access to the app from removing a volume as it is easy to do so. May be it could help if it would ask for the volume password before removing the volume. Currently its just a warning displayed which is also good but doesn't prevent anyone with unauthorized physical phone access from deleting a volume.

**Comment by hardcore-sushi** [comment]
If someone has physical access (and presumably unlocked) to your device then they can just clear the app storage or reinstall it to remove all volumes. This cannot prevented by the app. As such, implementing in-app lock would be useless.

**Comment by miphilip** [comment]
Yes correct. I thought its way too easy to be done within the app even for a kid. Regardless thanks for app, its amazing
