### ISSUE TITLE
Updating readme to mention reccomended NDK version for building

### ISSUE THREAD

**Issue by dhammel** [hardcore-sushi/DroidFS#33]
Hello,

as I've noticed, when attempting build if using some NDK version's (Such as the newer rc's, or even the newest stable 22, it'll error out during the compilation process. The latest version of the NDK I was able to get working was 21.3.6528147. Can you mention the reccomended version, maybe that of what you use to compile it? Sometimes this trial & error can get annoying.

Thank you :)

**Comment by hardcore-sushi** [comment]
Yes I don't know how to build openssl with NDK v22+. However it compiles with 21.4.7075529. This version is written in [app/build.gradle](https://github.com/hardcore-sushi/DroidFS/blob/e017fa85bd6cb7d264579348675e2d840ebd3d11/app/build.gradle#L7). Maybe I could add it the README.

**Comment by hardcore-sushi** [comment]
Done.
