### ISSUE TITLE
Version 1.5.0 corrupts new files

### ISSUE THREAD

**Issue by solokot** [hardcore-sushi/DroidFS#37]
Version 1.5.0 spoils newly added files: after a message about supposedly successful addition to the volume, it displays an error "Unable to load file". Files added to the volume by the 1.4.х application open normally in 1.5.0, but new files are unavailable (for exporting from the volume too).

Both the update installation and the clean installation with the creation of a new volume were tried. 100% error reproduction.

OS: MIUI 11 Andoroid 9

https://user-images.githubusercontent.com/25316928/123487507-b0df9780-d616-11eb-97da-efa570ffc52a.mp4

**Comment by hardcore-sushi** [comment]
Strange, it works fine for me. Do you got any errors in logcat ?

**Comment by hardcore-sushi** [comment]
OK, I found the bug: no permissions was set when creating new files in hidden volumes. I fixed this with [f17b0f2](https://github.com/hardcore-sushi/DroidFS/commit/f17b0f296f118a55cf18c2bc2dd9d2c5e64ca566). While waiting for the next release, you can create new files on volumes located in the shared storage.
