### ISSUE TITLE
Add thumbnails for pictures and videos

### ISSUE THREAD

**Issue by DvxBellorvm** [hardcore-sushi/DroidFS#38]
Hello,

I think it would be nice to have thumbnails for pictures and videos in files browser.
While this kind of files does not always have a talkative filename, for now they are a bit difficult to manage because we have to open each to figure out which one it is.

Thanks and congratulations for this nice project !

**Comment by hardcore-sushi** [comment]
Yes that's a good idea however it would require to read each files within the current directory. Since files must be decrypted first, this might be a bit slow. If I add this feature, I think I will make it optional so users can disable it to open large volumes.

**Comment by Android-PowerUser** [comment]
@hardcore-sushi 
RCX - Rclone for Android could be used as an example.  That works at a proper pace too.  The thumbnails could also be in DroidFS's cache (as an optional function).  It should be secure to run there without ROOT, I think. If you want ROOT you have to delete everything anyway.
Problem with RCX: It only makes sense for the cloud.  Despite the encryption, the app only keeps the configuration file to itself and the app only saves the hash.  Nevertheless, the app cannot even be secured with a fingerprint.  The hash is even written to the readable (internal) memory during export. That is only good for the cloud, but not for the internal one.

**Comment by hardcore-sushi** [comment]
Umh, I forgot this issue but DroidFS does show some thumbnails now, so I think we can close this issue.
