### ISSUE TITLE
Freezes when opening large volume

### ISSUE THREAD

**Issue by quixotique** [hardcore-sushi/DroidFS#41]
I have a Gocryptfs volume containing over 22,000 files, total size 2.6 GiB.  There are a dozen top level directories, and most of the files are about three or four directories deep.

When I open that volume in DroidFS, the app freezes in the browser page.  It just shows "Location: /" and "N//A" in the top bar and becomes unresponsive.  If I wait until the phone blanks its screen, then when I reawaken it, DroidFS has ceased trying to open the volume, and has returned to the home page with the three buttons, and is responsive again.

I enabled the "Keep volume open when the app goes in background" unsafe feature and tried again.  About 9 minutes after opening the volume, DroidFS populated the file browser with all the top level directories in the volume, and I could then successfully navigate the folders and view files.  However, this only happened twice.  On four other attempts, DroidFS remained frozen on a blank page for up to 30 minutes before I used "Force stop" on the app.

Once the volume was successfully open, there was a delay to close it as well.  After pressing OK on the "Warning! Are you sure...?" pop-over dialog, DroidFS froze for about 30 seconds with the dialog still visible, then returned to its home page.

Opening and closing a small Gocryptfs volume that contains about a dozen files works fine, with no freezes or delays.

**Comment by hardcore-sushi** [comment]
That's probably due to the volume size computation. Do you have the latest DroidFS version, v1.5.1 ? I'm trying to reproduce the bug but I can't manage to transfer so much file to my phone. How did you achieve that ? By using a SD card ?

**Comment by quixotique** [comment]
I am running version 1.5.1 of DroidFS on Android version 10.  You are correct; the Gocryptfs cipher folder is on an SD Card.

**Comment by hardcore-sushi** [comment]
When I open large volumes, DroidFS doesn't show the file listing immediately. However the UI is still responding: I can click on the "+" button, show menus etc. Is it your case or the app freezes completely (you can't interact with UI) ?

**Comment by quixotique** [comment]
In the case I reported, the DroidFS app becomes unresponsive.  If I try to swipe or press on anything, Android shortly pops up a dialog saying that the DroidFS app is not responding, and gives me the options to Wait, Force Stop, or Report.  I choose Wait.  I noticed that the times I tried to interact this way, DroidFS did not eventually succeed; as reported, I ended up doing a Force Stop after 30 minutes in these cases.

**Comment by hardcore-sushi** [comment]
OK, do get any errors in logcat ?

**Comment by hardcore-sushi** [comment]
I made the folder mapping optional with [5951237](https://github.com/hardcore-sushi/DroidFS/commit/5951237f2cc8f46faa4a51df3f2136f6ae6d12b9). Here is a test APK which includes this feature. Can you please test it and tell me if the app still freezes when disabling folder mapping ?
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Download link: https://drop.underworld.fr/r/pSLYcFAcP4#ejVylgTxtqAqhmdr9wSwc1MYNdCxwWHI1uLe4u1amnA=
SHA256: 4372730b8e67a4870c32ced72983cf91039424719ca7c14fcb029c12bc04aab4
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEvVYhR557dNNqQFvoAH+EEgEHGR4FAmDpdF0ACgkQAH+EEgEH
GR7fZA/6A4+dztjqkIBqH/6dAxg4qET4DV4Saj24Oxp0y4d2PfuPl8++1ITgux6s
nUlG2WYBWvTa20WtlwjDa2rEy8AchaH7TQv7vdLxD1Fr0w6p5n3Fwm5/gHjOwAXF
pekkdU/KyUH1zWJPNbj3vbXbJ/j0KgTE9NZtWMDaPWs/kRBzubNL6mTFO2Zt69QA
Ijxz0c+Q5p8Z4VQv+YGsldZyWyQO+2bG1xDB5ZxIl4YDGwmR1NKVSRfDPj1OkEjh
BN/5MIeHTyrh/zgzf+9JRmfKABYb/faxDaq1FFgvgiOhEZaFCQo8zg+cMalc7SgA
H2ZlTX36zjuX41f59qyf2JKvypKkT78QB8a9ahdsZ42uUDrhPhsxdxfn+Taz9a5C
L4cGlYrhT2M1Ems7En+PL5uUfc4bIWnyJaULjnUcAH56iojpg6i9/mquNbKn2Pr7
cQC0LA03g9FipZYRCrNPanJMYSOlvLJKDFPPmClfS9bt5doZCGbJ7ejrJ7q60+R8
zCXAV+4nkTBMBqGp41C3dRdd6u1s7pMKQ97zni8yYCLrguU0sEbMqWO5Gqi6Ed4Z
KeVNQwRgSy3eVPKjas/4Lf5VUD4KFH86fpT8DX3LXJ0/XPLw9Umii828mg3shlPd
rhPfQw5yr9bdLQK5A5k3XrkXttz7UtCu9ak08iwCvOB/OkCUSEQ=
=lEmp
-----END PGP SIGNATURE-----
```

**Comment by quixotique** [comment]
I installed the test APK, which shows Version 1.5.1 in Settings.  When I opened the large volume, I got the same freeze as before.  After waiting 30 seconds, I pressed the X icon in upper right to close the volume.  The pop-up immediately appeared: "Warning! Are you sure you want to close this volume?"  I pressed OK, and the popup froze with the "OK" button highlighted.  The app then became unresponsive, and Android eventually popped up the "DroidDS isn't responding" message with an option to Close or Wait.  Selecting Wait returned to the same frozen DroidFS popup.  I had to Force Stop the app to un-freeze it.

**Comment by hardcore-sushi** [comment]
Yes, but in settings there should be a "Map folders" option. Try to disable it.

**Comment by quixotique** [comment]
My mistake.  The test APK did not install... Android 11 popped up a very brief white message, saying "Something went wrong.  The app was not installed."  I do not have the Android Dev Kit installed at the moment, so I can't supply a logcat.

**Comment by hardcore-sushi** [comment]
Yes it's signed with my key. If you installed DroidFS from F-Droid, you will need to uninstall it first, or install the test APK on another device. Be careful: uninstalling DroidFS will erase all your hidden volumes. If you want I can rename the test APK so you can install it along side the original DroidFS version.

**Comment by quixotique** [comment]
A renamed APK would be best I think.

**Comment by hardcore-sushi** [comment]
OK, here is a renamed version:
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Download link: https://drop.underworld.fr/r/XnBrUhLgAA#FCkq3J5JKL7AhmdZQAe0l0/Zhh8SZlsKJVzt8RJAaac=
SHA256: 6050546c9ef767ef66ed76b58822f41f1a1a421bb5186192f7a65fdf7aef7ed8
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEvVYhR557dNNqQFvoAH+EEgEHGR4FAmDsFSIACgkQAH+EEgEH
GR56oA//X6iIsC8IsQCe1IMG/eH9X6cY6m/asMowP2fgWCo+utAPWYmxx7W2InlO
hTC0qZ07tXKI8tMdX1+I0pX92e7IJ6tKCap5S89XXMKew6fTecpDeRNJ2d5/HkkD
4fo5jGpwNVHJ7FjB6Aql89livoKhhIKP7AMDe9Yp9HqNh5XFq0MdWuA7BXmUk9or
kSgsQES2OhsDAyu6fSPsdsTyaSgxew6jwLTjnOMUyVfqWwfs+qlZwDDgUiRJpSW3
C8rAVHl7CYVEeZUGB0O27FspsXMeeg/c1x+C24Obpj73x/xKC3sxdSgN1M1djFC/
GIyGEFBiMsgEEGeqVFiaTFSvRjZ1ThF0XluR1pTSDGtcdHXSEA1cvEW+tAJ+MMp6
ReGXJIvxsVtYk1IwrUo5CIc1NVyCYoLxcRrtahWwxrpm6ilG0PpPWHmRqhsvzMTp
Q/SHvky5J2VZ5yuW5KemHDT/0ixUZ/kU/F4zeku5g12RViFbgHBb3sTuR/q0mmKC
c7Bfr8mrsobB3HKoX1BwAWbW7uATrvPS4be91J/fN5vBi7qGtLw9SlA5pF9W0qhu
AufTDC1eG0SNId1nbTzekI7OOtbpfNYOCi4QDrurSOwpikPvWvPaTk9tJpoPEAbf
uWAq3phRK5ah3MdJTVeFNukT4eYqPMs/i+u8tvQypkErHJ9FIFI=
=CScK
-----END PGP SIGNATURE-----
```

**Comment by quixotique** [comment]
I have tested the renamed test APK.  Now the large volume opens immediately and all the folders and files appear to be present.  Closing it also works immediately.

Apart from calculating the total cleartext size, what other features does Mapping a Volume provide?

**Comment by hardcore-sushi** [comment]
Current DroidFS version recursively walks inside all sub-directories to calculate their sizes. The "Map folder" option makes it optional. Now that I got confirmation that this was the problem, I will include this feature in the next DroidFS release. Therefore, this issue should be solved.

**Comment by quixotique** [comment]
Fantastic work!  Thank you.  I look forward to the next release... version 1.6 I am guessing (since it adds a new feature).
