### ISSUE TITLE
How to export files from a volume

### ISSUE THREAD

**Issue by shree-c** [hardcore-sushi/DroidFS#42]
Sorry this is a noob question.
I am not finding the way to export encrypted files out of the volume and make them normal files.
Please help me.
Thank you.

**Comment by shree-c** [comment]
Hey,
Got it. Needed to turn on 'allow decryption' option in settings. ;))

**Comment by shree-c** [comment]
However The keepassxc file is corrupted after exporting.

**Comment by hardcore-sushi** [comment]
No more corrupted ?
