### ISSUE TITLE
Unable to retrieve the selected path on removable media

### ISSUE THREAD

**Issue by BOB74j** [hardcore-sushi/DroidFS#47]
OS: Android 10
Device: Moto G5+
Platform: ARM64
DroidFS version: 1.5.2

Cannot select a path on removable 8GB exFAT flash drive connected via USB OTG. Attempting to choose the volume path on the flash drive shows "Error: Failed to retrieve the selected path".

**Comment by hardcore-sushi** [comment]
Yes it's an expected behavior. When you pick a file or a directory on Android, you get an URI. So DroidFS will try to extract a path from it, but if it's not a regular URI that point to a location in shared storage, it fails most of the time. Do you have a way to see what's the URI being retrieved when picking a folder on USB ?

**Comment by BOB74j** [comment]
> Yes it's an expected behavior. When you pick a file or a directory on Android, you get an URI. So DroidFS will try to extract a path from it, but if it's not a regular URI that point to a location in shared storage, it fails most of the time. Do you have a way to see what's the URI being retrieved when picking a folder on USB ?

URI to GoCryptfs config on USB OTG: content://com.android.externalstorage.documents/document/4839-8D98%3Acppcryptfs%2Fgocryptfs.conf

Interestingly, DroidFS is able to mount GoCryptfs volumes on external SD card. Copying the whole volume to my SD card allows the app to mount as read-only. URI is content://com.android.externalstorage.documents/document/EFFA-5B80%3Acppcryptfs%2Fgocryptfs.conf

**Comment by hardcore-sushi** [comment]
Awesome, how did you get this URIs ?
So I guess DroidFS can't retrieve the path if the volume is located on a USB OTG device. Since I don't have a USB OTG cable, I can't debug the problem. But maybe you can do it for me ? Are you able to compile the app from source ? Otherwise I can send you test APKs.

**Comment by BOB74j** [comment]
URIs were collected by opening the directory in the "Files" (com.android.documentsui) app, which is used as the default document storage provider when selecting a volume path through DroidFS. Long-pressing any file in that directory and selecting the share sheet brings up a Clipboard option through [MiXplorer](https://forum.xda-developers.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/), a file manager app I use more frequently than Files. The document storage URI can then be pasted to any text field.

I would be a little unsure compiling from source, so test APKs would be appreciated. Thanks for working on this issue! My use case requires accessing encrypted storage from USB OTG.

**Comment by hardcore-sushi** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

OK, I made a debug APK which will print some information in logcat. Don't expect it to work, I didn't modified the actual processing code. You can download it from here:

https://drop.underworld.fr/r/TNKgRcH6DF#hiQC6j+VTO+vKoi4vmdOKlUQiGHZhHj/RyygVYIMiMY=
SHA256: a9b83bf4660effffad88edb71a81d4a5de2375492baea03778146448ffa4eb1b

It's signed with my keys so if you installed DroidFS from F-Droid, you will probably need to uninstall the old version first (WARNING: this will remove all your hidden volumes).

Once installed, just select a volume on your USB-OTG storage from the app to reproduce the bug. Then send me the logcat output. You can get it using adb, Android Studio, or an awesome app like this one: https://f-droid.org/en/packages/com.dp.logcatapp
DroidFS will log with the tag "USB-OTG". You can look for it in the logcat output to check you are sending the right thing.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEvVYhR557dNNqQFvoAH+EEgEHGR4FAmEinQcACgkQAH+EEgEH
GR6Yow/+OvCNSaxuPR94oicuP/2ClkWpO4ErlZ8dkjyxDgoNASS49H3EnUsM63wo
qERjTkggoCbxf7paLlHQbFN7lkRVL3aG4sR9wa2OhRF2emK5XpeIzOzqTY9SfF9Q
1WNJn+/PCf5EOMH9QD72EZFzpx/5dun/HMTSisZNftLwUmh38pg5tAU3cBfHDlIq
rHZTIMcE7mXG90Z6P5Zcf+s4mG1oI6fSLw0W/+WnvbEW1Q/LR7eLoPWBHki+lkiu
Bg3sVCdYysBptXE65jn4YBpPQkVLmwNo3VfR94QxLIL9V2pNWGNEXaZbwyU0aNYP
iuIQw6nunpVvYQw89/Aovx+zlIJU7mWJ4ozLRoZNumCe8fpQ8Z/OSvJDAAjffkls
ewQ/h/ovxh0b+GrzLxC98txpbBxPmhRSdWL/iAFNh6mdYJrAfz5nEoiZY/k/Uc4x
k6cLhN8fx6BXQ7JiXWaNrT3KZ73z2Ynk21WIo1GfeXJfx/DSlaA+EAPqGEva4YbT
dK6NyWu7mJQhAhLJf+u0v18yYL0dzALUI8IEof7lD+LIBGDsXohCgrUhvSFFo5X/
xkdseEsDKKtnyUX9kbFHTHKbvg2uRxNK9Q6vGI8czePuhGXl+Uy80D35o0q+OBro
84uyxWNSb+NzcDZneCEV3C1ZlGvVq8meymRBVCXSJHXNsCm5A5g=
=T9dv
-----END PGP SIGNATURE-----
```

**Comment by BOB74j** [comment]
I have attached a logcat when selecting the OTG volume path and a logcat from selecting the volume on external SD card.

[logcat_extsd.txt](https://github.com/hardcore-sushi/DroidFS/files/7028217/logcat_extsd.txt)
[logcat_otg.txt](https://github.com/hardcore-sushi/DroidFS/files/7028218/logcat_otg.txt)

**Comment by hardcore-sushi** [comment]
That's what I thought, the USB-OTG device is not in the storage volume list that DroidFS can deduce a path from. Maybe a dirty string manipulation can do the trick...

**Comment by hardcore-sushi** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

OK, I modified the code so that it will try path manipulation if the first method fails.

You can download this APK from here: https://drop.underworld.fr/r/6gxdAyG7gE#XMFbQg2yibzRo27bd6eGYmVyXBxo6nL3CX/zhBpnhHs=
SHA256: 72d4594039fd6b43ed8903442c111684b0ea9f165e0fdcf10071ee215ec17cf0

I added some debug information so a logcat dump would still be appreciated.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEvVYhR557dNNqQFvoAH+EEgEHGR4FAmEmGkkACgkQAH+EEgEH
GR6evg//dKbR8hnmncrg0hpOQSDLMWctRr2MdBy0DPb8i+CcsKPdJ7jT81yG0c2t
TJ2GVTM0bLqCVjoOWy6geiUdLAMVnJmCw9brChsOuQVC4LyEgex4Oz06A6nJskYb
V8gUdFDw67GgwdEeFPWL5N2aqZzjROLtDOW6uEfLwztBFoOjh8Xh7c4eb7E7U+0U
dC2hBSJVuahILActqHEot4m+wSL+4QjdHcVIEjZ5quR7g/2E11bHGQknlKH+RKwC
h5lIRuKjuvR+OhuwmDzmdUssXF5tr33t0aNdtPwM3HX2KKNdtukFosKD4LMv9Fe5
+XXViSkd7thuVCeQ/J22ItWLyTErH/J60tRaYJFWZOUrCgu6qAwEz7JbozTeedW6
OmlbDem8YVLQ18IgqiqOVDOMloolHoFr8rEB8LC7asuNH4PjzTgDwM0ttXrFwfbb
pM7wU08Z3BQEYMNiBapt5E8haduDNq0P9u5ef6QSZujMpzzdNiwPAdPNO6dxdjPs
rZ6fjY3ABiPrMjaOzBtUNNV7jZFyQ275HDaUt6QIBvfDnP7VlHIs2y/cRYv+4TJ1
iUq4m6kMbzQeN/N3Fv/pKSXfBIQPhVOc9i3a14KgOwr13wqRxsxdz7KjAkf3ellA
MERikd87L44BH42VAMTNQqsdhFbGgVXeFCccxg7fC9BVfg2lUdc=
=L4ms
-----END PGP SIGNATURE-----
```
Thanks !

**Comment by jwmh** [comment]
What about as a file manager using Ghost Commander (latest version from the Google Play store)? and maybe some plugins for it, too.
Then copying/pasting the path used in GhostCommander to access the folder.

I did this on AndroidGO 8.1.0  to get the raw file access instead of the contentprovider URI.

**Comment by BOB74j** [comment]
> What about as a file manager using Ghost Commander (latest version from the Google Play store)?
> 
> market://details?id=com.ghostsq.commander
> 
> (Note-- be sure to use the Play Store, not fdroid, for latest version...)
> and maybe some plugins for it, too.
> Then copying/pasting the path used in GhostCommander to access the folder.
> 
> I did this on AndroidGO 8.1.0 to get the raw file access instead of the contentprovider URI.

Android 10, DroidFS v1.5.4 here, still no dice using any of the path formats provided by GhostCommander.

**Comment by lxsycht** [comment]
Hi. I don't know much about Android development but I hope this might be helpful.

Android 11 introduced some changes in how [storage is handled](https://developer.android.com/about/versions/11/privacy/storage), including the option to access files per direct file path, [as documented here](https://developer.android.com/training/data-storage/shared/media#direct-file-paths)

Could DroidFS possibly take advantage of this new feature?

**Comment by hardcore-sushi** [comment]
Yes it's planned to use [MANAGE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/manage-all-files) but that's only available on Android 11+.

**Comment by ramezquitao** [comment]
Hello, I'm having the same issue in a Samsung A70. Is there any way to access the external USB key in this devices?

Thanks

**Comment by BOB74j** [comment]
> Hi, on SD cards, DroidFS can write under `Android/data/sushi.hardcore.droidfs` through raw file paths. Does it work also with USB-OTG devices ?

Sorry for being a year late coming back to the party. On Android 10, DroidFS version 1.10.1, attempting to enter USB-OTG path `/mnt/media_rw/5088-7DB7` or `/storage/5088-7DB7/Android/data/sushi.hardcore.droidfs` to the Add volume menu returns the error _DroidFS doesn't have write access to this path. Please try another location._

The same path selected through storage access framework gives the error _Failed to retrieve the selected path._ In contrast to OTG devices, selecting the `Android/data/sushi.hardcore.droidfs` path on the SD card works (though other SD card directories, as expected, do not).

So it seems that on Android 10, OTG devices are still not compatible. Am I correct to interpret that OTG devices _may_ work on Android 11+ when [MANAGE_EXTERNAL_STORAGE](https://developer.android.com/training/data-storage/manage-all-files) is implemented in Droid_FS?

**Comment by hardcore-sushi** [comment]
Thanks you for feedback. I don't know if it's going to work at all, but it's planned to be implemented for DroidFS v2.0.0 (stable).

**Comment by BOB74j** [comment]
OTG volumes may now be mounted on latest 2.0.0 release! Read/write access works, no need to place volumes under /Android/data/sushi.hardcore.droidfs Tested on Galaxy S23/Android 13.

**Comment by rootdeck** [comment]
I have read issue #47 and I thought usb otg is working since v2 but I still get this error "DroidFS doesn't have write access to this path. Please try another location" when I try to add a volume from the usb. I tried it both on android 11, 13 and it shows the same error. Thank you for the great app.

**Comment by hardcore-sushi** [comment]
What's your device model and ROM ?

Make sure that DroidFS is granted "All files access" permission and that your drive is mounted read/write.

Please show your logcat while reproducing the bug.

**Comment by rootdeck** [comment]
I manage to make it work using v2.0.2 on android 13

1. Plug in the USB, Open the app and try to mount/create the volume. 
2. The error "DroidFS doesn't have write access to this path. Please try another location" will pop up.
3. close the app 
4. Open the app. Try to mount it again and it will work.

I don't know why I need to close the app but it works when I do that. no luck on android 11 so I just update to 13.

**Comment by hardcore-sushi** [comment]
OK, that's weird. Can you please show your logcat of the bug?

**Comment by gambassador** [comment]
Hi Hardcore-Sushi! Thanks for the great app, it works wonderfully for most purposes. But I am reviving this year-old thread as I seem to have the same problem with a USB device (Sandisk 2TB disk) - DroidFS gives me the error message "DroidFS doesn't have write access to this path. Please try another location." 

The USB device is directly connected to the Android mobile (Pixel 8). Other apps can write fine on the drive and actually DroidFS itself also can write to the disk - it proposed and succeeded to save the logcat in the very same folder where I tried to create a volume. The "open and close and open" the app solution by the previous poster did not work for me. 

Logcat attached. Thanks again for all your efforts!

[DroidFS_2024-11-28_15_34_45.log](https://github.com/user-attachments/files/17949855/DroidFS_2024-11-28_15_34_45.log)

**Comment by hardcore-sushi** [comment]
What Android version are you using? Were you able to open it in the past? If so, which is the latest version of DroidFS that is working?

What path is displayed in the text field after selecting your USB device? Is it the same as when you access your USB device from a file explorer? If it's different, can you open a volume in DroidFS by directly copy-pasting the correct path instead of choosing a folder?

Saving the logcat use a different API so it's expected to be working fine.

**Comment by gambassador** [comment]
Thanks Matéo, your suggestion fixed it. 

> What path is displayed in the text field after selecting your USB device? Is it the same as when you access your USB device from a file explorer? If it's different, can you open a volume in DroidFS by directly copy-pasting the correct path instead of choosing a folder?

Using 'pick a directory', DroidFS shows: 
`/storage/C7D3-E1DA/Par
`
CxFileExplorer shows:
`/mnt/media_rw/C7D3-E1DA/Par
`

Copying this into DroidFS indeed works! So my problem seems to be solved, thank you!

Just to help debug the issue for the future: 

> What Android version are you using? Were you able to open it in the past? If so, which is the latest version of DroidFS that is working?

Android 15, Build AP3A.241105.007

> Saving the logcat use a different API so it's expected to be working fine.

I'm not sure how to do this. If it's still helpful to clarify the issue please let me know and I can try to do it.

**Comment by hardcore-sushi** [comment]
Great. I tried to improve the path resolving process to fix this issue. Could you try this test APK?

https://upload.disroot.org/r/0AutMLg1#Yn+yqHCdoLJ134alh7uKj5cbWEayo6djSHGvAAyDzME=

<details>
<summary>PGP signature</summary>

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

SHA256: ad57d113ea5413837b11e445cfc8a0f03b92e75916f7e89419502b04f73ef613
-----BEGIN PGP SIGNATURE-----

iHUEARYIAB0WIQS2Tv6GzuHQVPCCFxGv44Q0SkXhOgUCZ0s6xgAKCRCv44Q0SkXh
OkxVAP9ABeB2SJBFcxCg3nSntgykdHTRHjOgaiJYFZCQYEx7YwD+P6T9uj53X271
MtZ9ohdyRdbZRqRnWKV+r4WKQjxgIQ8=
=hKOM
-----END PGP SIGNATURE-----
```
</details>


> > Saving the logcat use a different API so it's expected to be working fine.

> I'm not sure how to do this. If it's still helpful to clarify the issue please let me know and I can try to do it.

You don't have to do anything. Sorry, I meant the DroidFS built-in logcat saving feature uses a different API that doesn't need to resolve the path so it should always work, even if adding a volume fails.

**Comment by zdrawko420** [comment]
> Great. I tried to improve the path resolving process to fix this issue. Could you try this test APK?
> 
> https://upload.disroot.org/r/0AutMLg1#Yn+yqHCdoLJ134alh7uKj5cbWEayo6djSHGvAAyDzME=
> 
> PGP signature
> > > Saving the logcat use a different API so it's expected to be working fine.
> 
> > I'm not sure how to do this. If it's still helpful to clarify the issue please let me know and I can try to do it.
> 
> You don't have to do anything. Sorry, I meant the DroidFS built-in logcat saving feature uses a different API that doesn't need to resolve the path so it should always work, even if adding a volume fails.

Can you provide that test apk again, please?
Wanna try it as I face same issue on LineageOS 22.2 (Android 15).
Thank you!
