### ISSUE TITLE
Crash when opening volume

### ISSUE THREAD

**Issue by wannaskoo** [hardcore-sushi/DroidFS#49]
OS: Android 10
Device: OnePlus 6
Platform: ARM64
DroidFS version: 1.5.3

Tried with arm64 and universal apk, it crashes when trying to open a volume ( it worked fine previously).
Crash log attached.
[logcat_09-05-2021_12-10-55.txt](https://github.com/hardcore-sushi/DroidFS/files/7111404/logcat_09-05-2021_12-10-55.txt)

**Comment by hardcore-sushi** [comment]
Oh yes I got it too.
It works fine in debug mode. I will try to rebuild the release APK.

**Comment by hardcore-sushi** [comment]
Fixed with [d36910a](https://github.com/hardcore-sushi/DroidFS/commit/d36910ac190d412b5e06ac5eb256054aa609b239). The next release should work.
