### ISSUE TITLE
please expand built-in photo taking camera to video and audio recorder mode as well

### ISSUE THREAD

**Issue by User1l0** [hardcore-sushi/DroidFS#51]

**Comment by hardcore-sushi** [comment]
Yep it's planned.

**Comment by hardcore-sushi** [comment]
OK here is the current situation:
CameraX uses the MediaMuxer API to create MP4 file from audio and video. However this API (like many others in the fucking Android project) requires a seekable file descriptor as output. It means we cannot pass an in memory pipe or a local socket to bypass this restriction. So I decided to do the muxing process with FFmpeg instead, but I got a problem with audio: the AOSP player only plays video and ExoPlayer crashes. The fact is Cryptocam has also [the same issue](https://gitlab.com/cryptocam/cryptocam/-/issues/27) so I don't think it's related to the ffmpeg API usage.

If anybody want to investigate the issue:
FFmpeg build script: https://forge.chapril.org/hardcoresushi/DroidFS/src/branch/video-recording/app/ffmpeg/build.sh
The muxer replacing MediaMuxer in VideoCapture: https://forge.chapril.org/hardcoresushi/DroidFS/src/branch/video-recording/app/src/main/java/sushi/hardcore/droidfs/Muxer.kt
The FFmpeg API calls: https://forge.chapril.org/hardcoresushi/DroidFS/src/branch/video-recording/app/src/main/native/libmux.c

**Comment by hardcore-sushi** [comment]
I ended up getting it to work, but it requires enabling the ffmpeg encoders, so the final APK for one ABI is about 2MB larger. Any better solution is welcome!
The next DroidFS version will include this feature.
