### ISSUE TITLE
Bug in light mode

### ISSUE THREAD

**Issue by Android-PowerUser** [hardcore-sushi/DroidFS#57]
v1.7.0 If the dark mode is not switched on, the writing can no longer be read because it then has the same color as the background.  No matter what design. 
Android 11 Samsung german

**Comment by hardcore-sushi** [comment]
Lol you're right, it should be fixed with 4f8bf860e0eaf72ea7b65294918013bef1df1ce5. I updated the releases, please can you confirm it works fine now?

**Comment by Android-PowerUser** [comment]
Unfortunately, I have no programming experience and cannot compile it.

Hardcore Sushi ***@***.***> schrieb am Do., 11. Nov. 2021,
22:53:

**Comment by hardcore-sushi** [comment]
I updated the releases, just download the new version.
