### ISSUE TITLE
Files ≥ 48 MB do not get thumbnails

### ISSUE THREAD

**Issue by Android-PowerUser** [hardcore-sushi/DroidFS#58]

**Comment by hardcore-sushi** [comment]
Yes it's a normal behavior: https://github.com/hardcore-sushi/DroidFS/blob/4f8bf860e0eaf72ea7b65294918013bef1df1ce5/app/src/main/java/sushi/hardcore/droidfs/adapters/ExplorerElementAdapter.kt#L134
All files larger than 50 MB will not be loaded, so you will not see thumbnails of these files. I did this to avoid overloading the memory. Any better idea is welcome.

**Comment by Android-PowerUser** [comment]
DroidFS offers the option for a "hidden volume" in the app data.  DroidFS
could create a hidden volume itself and store thumbnails there, as happens
with /sdcard/DCIM/thumbnails/ and would then only have to load it once.

Hardcore Sushi ***@***.***> schrieb am Fr., 12. Nov. 2021,
09:25:

**Comment by hardcore-sushi** [comment]
Good idea, but the initialization of this volume could still overload the memory.

**Comment by Android-PowerUser** [comment]
Just like a file is temporarily buffered during playback, you could only
load the first 10 seconds and then create the thumbnail like
https://play.google.com/store/apps/details?id=com.alphainventor.filemanager
. It probably doesn't matter how big the file is.

Hardcore Sushi ***@***.***> schrieb am Fr., 12. Nov. 2021,
10:09:

**Comment by hardcore-sushi** [comment]
Thumbnails are currently created with [Glide](https://github.com/bumptech/glide), and it looks like it needs the whole file to create the thumbnail. Maybe I could use a more specialized library.

**Comment by Android-PowerUser** [comment]
In RCX - rclone for Android
https://github.com/x0b/rcx
https://play.google.com/store/apps/details?id=io.github.x0b.rcx&hl=en
thumbnails with encryption also work for large files. But it is more
suitable for the cloud than for encryption on the smartphone.

File content <https://rclone.org/crypt/#file-encryption> encryption is
performed using NaCl SecretBox
<https://godoc.org/golang.org/x/crypto/nacl/secretbox>, based on XSalsa20
cipher and Poly1305 for integrity.

Hardcore Sushi ***@***.***> schrieb am Fr., 12. Nov. 2021,
13:36:

**Comment by hardcore-sushi** [comment]
RCX only loads thumbnails of files smaller than a defined size (20MB by default), like what DroidFS currently does. It also caches thumbnails in the app cache folder in plain text. But obviously DroidFS can't do this.

**Comment by Android-PowerUser** [comment]
That would be fine in the app-data without [root] and high Android-version.
In addition, files over 200MB can be loaded without any problems.

Hardcore Sushi ***@***.***> schrieb am So., 19. Dez. 2021,
19:50:

**Comment by hardcore-sushi** [comment]
It all depends on the number of files in the current directory. I have to implement a thread pool with a job queue and load thumbnails one by one in each threads. I think it would be the best solution.
