### ISSUE TITLE
missing files and folders

### ISSUE THREAD

**Issue by Miladhsp** [hardcore-sushi/DroidFS#65]
I create a new volume and add the parent folder to the volume and lose all the sub files and sub folders of parent folder data

**Comment by hardcore-sushi** [comment]
OK, can you give more details please? Did you imported a folder from the shared storage? Did you get any errors in pop-up or in logcat? Do you see some encrypted files inside the volume folder? (via an external file explorer)
Also, which DroidFS version do you use?

**Comment by Miladhsp** [comment]
internal storage.
no errors.
selectedFolder\subFolder\<encryptedVolume>  .
1.7.0


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hardcore-sushi** [comment]
OK but which files are in the encrypted volume folder? Do you see the lost files if you open the volume with the original gocryptfs program?
Can you reproduce the bug?

**Comment by Miladhsp** [comment]
mp3 pdf and ets 
im searching for that encrypted file but there is no file.( because this app move folder or file in to encrypted file and not copy it)
please test that process

**Comment by hardcore-sushi** [comment]
Sorry but I can't help you if you refuse to answer my questions. I will close this issue if you can't give me more details.
