### ISSUE TITLE
move the open container button

### ISSUE THREAD

**Issue by OmlineEditor** [hardcore-sushi/DroidFS#66]
after entering the password, you need to click on the open button, but the button is closed by part of the keyboard. I ask you to move the button above so that it is convenient to press open

![fs](https://user-images.githubusercontent.com/13348933/148247760-9ee820ff-5dbb-4826-be15-16974b87aa29.jpg)

**Comment by hardcore-sushi** [comment]
Yes but there isn't enough room for it. Also, you can press enter on your keyboard to open the volume, this should also work.

**Comment by OmlineEditor** [comment]
if there is not enough space, just move down the list of stored containers. Why do I need a button if I can't press it? it's not logical.

**Comment by hardcore-sushi** [comment]
I think the real problem is that we can't scroll the page, although it seems to work fine on the volume creation page. I'll investigate this.

**Comment by OmlineEditor** [comment]
it is better to add a scroll and a transfer button, we will kill two birds with one stone

**Comment by hardcore-sushi** [comment]
There isn't so much scroll buttons on Android. And what do you mean by a "transfer button"?

**Comment by OmlineEditor** [comment]
English is not my language. Maybe I'm not saying it right

"transfer button" - moving the button, see the picture

![move](https://user-images.githubusercontent.com/13348933/148416330-3445aee5-c884-40d0-8ecc-70450d7bb5ae.jpg)

**Comment by hardcore-sushi** [comment]
Oh OK, but I find the second layout a bit weird. I would appreciate to have opinion from UI designers.
I'll fix the scroll bug, so we could at least scroll the page to reach the button even if the keyboard is open.

**Comment by OmlineEditor** [comment]
the open button is as close as possible to the login and password input field this is the most correct option.

**Comment by hardcore-sushi** [comment]
I don't know, because we want the user to see the warning message before clicking on open. Furthermore, clicking on the button is the last thing we do on this page so I find it relevant to put it at the bottom.

**Comment by OmlineEditor** [comment]
I agree with you. talk to other users and show them which option of the button they think is better

**Comment by ralaud** [comment]
In my opinion, one time warning popup after first install and if I open unsave features settings would be enough.

Or if a permanent warning text is necessary, then I would suggest a text spoiler (a button which hide and open a text, like in a forum).

Like this maybe:
![droidfs-sample.png](https://user-images.githubusercontent.com/27868982/148751308-3b1d5742-abbb-4158-a901-839be5dd6029.png)

**Comment by hardcore-sushi** [comment]
Yes a one-time warning could be sufficient. But would it be relevant to have the open button above the list of saved volumes?

**Comment by OmlineEditor** [comment]
the name of the button can be changed to a more convenient and understandable one:
**_"click to read the warning"_**

I like the idea of the warning button

**Comment by ralaud** [comment]
> Yes a one-time warning could be sufficient. But would it be relevant to have the open button above the list of saved volumes?

If we save more than 4 or 5 volume path's then we may have the same problem again. So I think every saved volume path would move the open button down.

After 4 saved path's the open button is maybe overlapped a bit
![IMG_20220110_182715.jpg](https://user-images.githubusercontent.com/27868982/148811178-19506046-b0f5-4292-b52b-1485045a12b2.jpg)

After 5 saved path's we have the same problem
![IMG_20220110_182821.jpg](https://user-images.githubusercontent.com/27868982/148811307-c85564a6-0b4c-444a-acaa-834bfeb7a146.jpg)

I think it is not worse if the saved path's will be overlapped from the keyboard. Because we have to tab on the saved path first, before we tap on password field and the keyboard pops up.

**Comment by OmlineEditor** [comment]
all right. At the beginning, at the time of selecting the encrypted volume, there is no keyboard and therefore no problem. The open button will be above the list of paths and therefore the second problem is solved

**Comment by hardcore-sushi** [comment]
I fixed the scrolling issue (https://user-images.githubusercontent.com/68192412/148999701-c34bc39f-32a0-472d-8933-a6cf1da03053.mp4). Now we can reach the button even if it's hidden by the keyboard by scrolling the page. Do you think it's enough or should it still be moved above the volume list?

**Comment by OmlineEditor** [comment]
scrolling is good, but it doesn't add to the opening speed. move the button above the list of all containers so you won't need to scroll

**Comment by hardcore-sushi** [comment]
If your goal is speed, just press enter on your keyboard so your finger doesn't need to travel a long distance to tap the button. I'm afraid to break the UI logic if I move the button above the volume list.

**Comment by OmlineEditor** [comment]
you won't break the logic. you will make a more user-friendly interface.

**Comment by ralaud** [comment]
> I fixed the scrolling issue (https://user-images.githubusercontent.com/68192412/148999701-c34bc39f-32a0-472d-8933-a6cf1da03053.mp4). Now we can reach the button even if it's hidden by the keyboard by scrolling the page. Do you think it's enough or should it still be moved above the volume list?

If the warning text will stay, then I think the position of the open button should not be changed. 

Your scroll fix already solved the main problem. So we do not need to change the UI so fast, discussing UI changes would be better with more user feedback later.
Thanks for your fix!

**Comment by OmlineEditor** [comment]
I understand that you want to protect users and and so that they read the warning. But at the same time, the appearance and usability suffer. I ask you to think about the possibility of changing the user interface in the future

**Comment by hardcore-sushi** [comment]
I published the scroll fix (f15b17c936447f10260feccab95ef0ce74e628cc), I'm closing this issue now.
