### ISSUE TITLE
Entering the password immediately for selected one container

### ISSUE THREAD

**Issue by OmlineEditor** [hardcore-sushi/DroidFS#68]
most often you need to run the program and open the container. I ask you to implement the function when, when the program starts, a password entry window opens immediately for a specifically selected one container. it's easier and faster this way.

**Comment by hardcore-sushi** [comment]
True, I planned to make a re-design of the main page UX.

**Comment by hardcore-sushi** [comment]
With DroidFS v1.9.0 we only need one click to open a volume. I think I can close this issue.
