### ISSUE TITLE
mount to filesystem?

### ISSUE THREAD

**Issue by misterhsp** [hardcore-sushi/DroidFS#7]
@hardcore-sushi 
I have to ask again. Do you plan to add mount in Droidfs for rooted devices, yes or no?

thanks...

**Comment by hardcore-sushi** [comment]
I might add this feature if several people want it.
Meanwhile, tell me what you want to do by mounting volumes. Maybe we can find a workaround.

**Comment by misterhsp** [comment]
...yes or no?

**Comment by hardcore-sushi** [comment]
Prout !

**Comment by misterhsp** [comment]
pff
