### ISSUE TITLE
error when creating files with the same names

### ISSUE THREAD

**Issue by OmlineEditor** [hardcore-sushi/DroidFS#70]
inside the container, you can create two files or two folders with the same names but with different case

I can create two files
abc.txt
ABC.txt

this is incorrect from the point of view of the file system.

I ask you to ignore the case and consider two files with the same names - completely the same and forbid creating them.

**Comment by hardcore-sushi** [comment]
Sorry, but that's completely legit on Linux file-systems like ext4. Moreover, the original gocryptfs code allows it too. So I definitely won't implement this.

**Comment by OmlineEditor** [comment]
then you need to make a warning or add information about it in the description

**Comment by hardcore-sushi** [comment]
Why? It's the normal behavior on almost all UNIX like machines.

**Comment by OmlineEditor** [comment]
I plan to transfer some of the containers to windows, but this is not possible for him.

**Comment by hardcore-sushi** [comment]
The problem doesn't come from DroidFS or gocryptfs, but from Windows ;)

**Comment by OmlineEditor** [comment]
![Okay_meme](https://user-images.githubusercontent.com/13348933/148415087-2885f662-5794-4299-9f73-d70c746f8aff.png)
