### ISSUE TITLE
more beautiful and clear camera buttons

### ISSUE THREAD

**Issue by OmlineEditor** [hardcore-sushi/DroidFS#74]
I ask you to change the buttons for a more convenient and better perception

the picture shows the buttons from the program Open Camera: https://f-droid.org/ru/packages/net.sourceforge.opencamera/

![bnt](https://user-images.githubusercontent.com/13348933/148699281-72ac0db1-209a-4786-ae7a-d30c2ebfe811.jpg)

**Comment by hardcore-sushi** [comment]
Sorry but I actually prefer the DroidFS's buttons 😄. What do you find bad in those?

**Comment by ralaud** [comment]
> Sorry but I actually prefer the DroidFS's buttons 😄. What do you find bad in those?

First time I used camera in DroidFS, I was wondering if I use photo or video mode at the moment. 

At the position of this icon:
![Imagepipe_0.jpg](https://user-images.githubusercontent.com/27868982/148754714-acea2d66-dd40-4db7-aa98-cff8cc6c3bed.jpg)

I would expect in photo mode a [photo camera icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aphoto_camera%3A) and in video mode a [videocam icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Avideocam%3A). When I saw videocam icon in both modes, I was a bit confused.

**Comment by hardcore-sushi** [comment]
@ralaud you're right, I should fix this. However I think it would be better to have a video icon in photo mode and a photo icon in video mode to indicate that the button will switch mode.

**Comment by OmlineEditor** [comment]
the side button in the form of a movie camera needs to be changed, and the central button in the form of a circle should be changed to cameras and a video camera, depending on what is being filmed now

![changes only the color](https://user-images.githubusercontent.com/13348933/148785440-81f74da0-2c00-49c8-9434-7d240a66a168.jpg)

**Comment by ralaud** [comment]
> @ralaud you're right, I should fix this. However I think it would be better to have a video icon in photo mode and a photo icon in video mode to indicate that the button will switch mode.

That would be fine for me.


But I think most of camera apps try to clearly show which mode is in use at the moment.

Here some examples:

Google Camera
![Imagepipe_1.jpg](https://user-images.githubusercontent.com/27868982/148804375-5b77756a-780a-4458-8c6a-044e07f584ff.jpg)

Samsung Camera
![Imagepipe_2.jpg](https://user-images.githubusercontent.com/27868982/148804598-719ce7c8-72b8-493c-a37b-a9f4522f742c.jpg)

Lineageos Snap Camera
![Imagepipe_3.jpg](https://user-images.githubusercontent.com/27868982/148805166-511a0ef3-7dc2-46a3-8033-512df841673d.jpg)

![Imagepipe_4.jpg](https://user-images.githubusercontent.com/27868982/148805192-e7ee69a3-ef16-4d14-a73e-1577d8250d94.jpg)

Off-Topic:
Maybe audio only recording could be integrated in an UI like Lineageos Snap Camera too. So no new UI design would be necessary for audio recording later (just video UI with audio only sequence, while indicating audio mode with [mic icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Amic%3A).

**Comment by OmlineEditor** [comment]
right. use the microphone icon in the center for the place of the circle when sound is being recorded.
when recording a video, use the video camera icon in the center instead of the circle. and when the photo is taken the camera photo icon

**Comment by hardcore-sushi** [comment]
What we get after 5d6f53b37a637d604c16a3c92ec1a3fcf2ec3598:

![demo](https://user-images.githubusercontent.com/68192412/149006295-a5f0c2d1-f15c-4aa2-b4b1-91184599bcb1.gif)

Is it still too confusing?

**Comment by OmlineEditor** [comment]
yes confusing. it's hard for me to understand what is happening on the screen.
we leave the left button on the side as it is, we do not touch
it, in the center we change the circle to the camera if we take a photo, and we change the red circle to the video camera if we take a video.

**Comment by ralaud** [comment]
> What we get after 5d6f53b37a637d604c16a3c92ec1a3fcf2ec3598:
> 
> ![demo](https://user-images.githubusercontent.com/68192412/149006295-a5f0c2d1-f15c-4aa2-b4b1-91184599bcb1.gif)
> 
> Is it still too confusing?

For me your fix is fine. Thank you!

**Comment by hardcore-sushi** [comment]
OK, I leave the UI like this for now. I don't want to change the main button style.

**Comment by OmlineEditor** [comment]
It's hard to understand what's going on. the central round button is obscure
on the side there is a switch button on the photo, and in the center is what is happening now. Similarly, for a photo, there will be a photo camera in the center, and a video camera with an arrow on the side

![1](https://user-images.githubusercontent.com/13348933/149016478-7bcb33e6-0aa7-42be-b667-2f385fedd316.PNG)

**Comment by hardcore-sushi** [comment]
Yeah but what you want is not modern UI. I find this a little ugly. Sorry but I won't implement this. However you're free to fork the app to make your changes ;)

**Comment by OmlineEditor** [comment]
I drew in paint and that's why it turned out ugly, I can't branch the application because I don't know how to program for android

**Comment by ralaud** [comment]
I think it is better to switch directly to modern UI later, due to may new modes will be added later then modern UI is necessary.

Changing the UI to another UI which also is restricted to two modes, will result in more work, because it is also not designed for multiple camera modes.
For example if audio mode will be added in the future, then an UI with multiple modes will be necessary.

So I think this UI is fine for two modes.

**Comment by OmlineEditor** [comment]
if there is only sound recording, you will make a microphone button in the center and simply hide the other interface elements. These are minimal changes.

**Comment by hardcore-sushi** [comment]
I think I won't implement audio-only recording in the camera activity. I'll use a new dedicated activity because the controls won't be the same. So I won't change the camera activity UI because of audio recording.

**Comment by OmlineEditor** [comment]
well, make a new functionality, if there are ideas how to improve it, I'll tell you
