### ISSUE TITLE
problem when starting text editing

### ISSUE THREAD

**Issue by OmlineEditor** [hardcore-sushi/DroidFS#77]
- creating an empty file: demo.txt
- opened it
- to start editing, click on the very top in the first empty line, the very top is a very narrow place

this is inconvenient when a large empty field is not used, I click but nothing happens and the keyboard does not open and editing does not begin 

I ask you to change the logic of work. If the user clicks below the **_last line_** on an **_empty field_**, then the editing opens and starts from the last line.

**Comment by canary5** [comment]
I even thought its doesnt work at all. Imported some txt files as source for txt:)

**Comment by hardcore-sushi** [comment]
Yeah I know. I got some problem with the layout. I'll try to fix that.

**Comment by hardcore-sushi** [comment]
Fixed with b366fa187733f607afcf921f09e4446d7f356425.
