### ISSUE TITLE
f-droid

### ISSUE THREAD

**Issue by bingoxo** [hardcore-sushi/DroidFS#8]
hi , can you please consider adding your app to f-droid , it would have bigger audience and allow us to get auto updates

**Comment by hardcore-sushi** [comment]
Check that: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7600

**Comment by hardcore-sushi** [comment]
I'm very happy to tell you that DroidFS is now available on the official F-Droid repo !
https://f-droid.org/en/packages/sushi.hardcore.droidfs/
