### ISSUE TITLE
SKS pool no longer available

### ISSUE THREAD

**Issue by TeFiLeDo** [hardcore-sushi/DroidFS#86]
`hkp://pool.sks-keyservers.net` is no longer available. Please make your key available elsewhere.

Thank you

**Comment by hardcore-sushi** [comment]
It should be still available on other keyservers (`hkps://pgp.mit.edu`, `hkps://keyserver.ubuntu.com`...) I'll update the PGP stuff soon.

**Comment by TeFiLeDo** [comment]
Alright, thank you, I was able to get the key from those servers.
