### ISSUE TITLE
DroidFS cannot delete the original file.

### ISSUE THREAD

**Issue by ELForcer** [hardcore-sushi/DroidFS#94]
Smartphone: Redmi Note 4
Android: 7.0 NRD90M

DroidFS cannot delete the original file if it is large or if multiple files have been imported. The notification window says:
Delete 0/2 or more files.

Tested on small files, it deletes successfully.
Or does it clean up the entire file?

**Comment by hardcore-sushi** [comment]
Yes if you wipe a file after importing it, DroidFS will completely rewrite it twice before deleting it. How big are your files? Are they finally deleted after some time?

**Comment by ELForcer** [comment]
Is it possible to make the option to rewrite files after moving? So that you can choose a normal delete or delete with rewrite.

**Comment by hardcore-sushi** [comment]
The wipe feature is there because it's a security feature. If you don't want to wipe your files, just delete them with a file explorer.

OK, I'll try to determine if the application can erase 1 GB files.

**Comment by hardcore-sushi** [comment]
Wiping a 1GB file works fine for me.

**Comment by ELForcer** [comment]
Maybe it takes too long for me to delete. Therefore, I propose to still make an option between the wipe of the file and the usual deletion. By default, the option can be left as wipe, and anyone who wants to speed up import can turn off this option if the source files are stored on the same disk as the encrypted volume. They will be overwritten anyway.

**Comment by hardcore-sushi** [comment]
I'm not going to add this option because users can do it with a regular file explorer.
